### ISSUE TITLE
Exception occurred: Error in Line 987:63

### ISSUE THREAD

**Issue by patdiez** [marcusraitner/COVID-19-Dashboard#100]
Seit heute bekomme ich folgende Fehlermeldung mit Version 1.11.

![Screenshot 2022-01-09 at 10 02 02](https://user-images.githubusercontent.com/52236155/148675989-5ec2539c-cff8-429c-b020-c5b995af291e.png)

mit Version 1.10.3 hatte ich auch eine Fehlermeldung - war nur eine andere Zeile. 
Hat jemand eine Idee?

**Comment by eddy-tec** [comment]
Eventuell ein Problem mit der api ?

![image](https://user-images.githubusercontent.com/97383047/148676983-228a501d-cfe3-4795-acd9-cc751aaa2344.jpeg)

Habe aber auch das gleiche Problem...

![image](https://user-images.githubusercontent.com/97383047/148677026-e009d3c2-769a-4d49-8433-8aa9408c7f35.jpeg)

**Comment by pin00b** [comment]
![A7BC93AB-53F8-4092-98E9-B00FE6A0B2AF](https://user-images.githubusercontent.com/61549899/148677277-34a521fe-a78f-4e09-9143-1aff0bcd4024.png)

v1.11.0

**Comment by lululasse** [comment]
Gleiches Problem auch hier.

**Comment by marcusraitner** [comment]
Ist ein Problem in der API. Ihr könnt als Workaround mit `hosp=n` als Parameter diesen Aufruf umgehen. Vermutlich geht es morgen dann so oder so wieder.

**Comment by pin00b** [comment]
> Ist ein Problem in der API. Ihr könnt als Workaround mit `hosp=n` als Parameter diesen Aufruf umgehen. Vermutlich geht es morgen dann so oder so wieder.

👍 und Danke auf diesem Weg für das nach wie vor großartige Dashboard!

**Comment by eddy-tec** [comment]
Auch von mir mal danke für das super Widget 👌🏻

Also bei mir läuft es wieder... ✅

**Comment by patdiez** [comment]
Ja scheint wieder zu laufen! Vielen Dank und ich werde die Gelegenheit auch mal gleich nutzen und einen Kaffee spenden. ☕️

**Comment by nils-mac** [comment]
Bei mir läuft es jetzt auch wieder.

**Comment by lululasse** [comment]
Ja, läuft auch hier wieder rund! 
Ist wirklich ein tolles Dashboard! Danke Marcus!

**Comment by marcusraitner** [comment]
Sehr gut! Danke für eure Wertschätzung und die Kaffees!
