### ISSUE TITLE
1./2./3. Impfungen

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#101]
Hallo Marcus,
Heute morgen sieht die Impfstatusleiste rechts komisch aus. Die Boosterimpfungen sind ganz weg. Wieder ein API oder Cache Problem?
Gruß
Klaus

**Comment by marcusraitner** [comment]
Ja, mal wieder das Excel des RKI (vermutlich ein Praktikant der daran rumspielet ;-)) siehe hier: https://github.com/marlon360/rki-covid-api/issues/381

**Comment by marcusraitner** [comment]
Passt wieder

**Comment by lululasse** [comment]
Danke! 💯
