### ISSUE TITLE
Hospitalisation Data ubdefined

### ISSUE THREAD

**Issue by lasolue13** [marcusraitner/COVID-19-Dashboard#103]
![62C9F2B5-A4E8-4398-9547-F208D07E847B](https://user-images.githubusercontent.com/15649002/152186384-3ca8f722-1ad2-4bc6-98fb-0dc03c181243.jpeg)

**Comment by nils-mac** [comment]
Die CSV Datei des RKI, welche für die Internetseite corona-zahlen.org als Datengrundlage benutzt wird ist zu groß geworden. Deswegen werden keine Daten in der Datei mehr angezeigt. Ich hoffe das RKI überlegt dich da etwas...

**Comment by lasolue13** [comment]
Ah, danke für das schnelle Feedback! Als kleines Update ist der Fehler auch in der aktuellsten Version aufgetreten:

2022-02-02 16:46:08: Error on line 987:63: TypeError: undefined is not an object (evaluating 'hospitalizationData.data[bundesLand]')

**Comment by marcusraitner** [comment]
Siehe unter anderem hier: https://github.com/marlon360/rki-covid-api/issues/388 

Und ja: es ist unsäglich, dass wir hier in Deutschland diese Daten per CSV zur Verfügung stellen und dass das dann "zu groß" wird. Das sind Zustände wie in der inneren Mongolei ;-)

**Comment by marcusraitner** [comment]
Als Workaround kann ich derzeit nur anbieten mittels Parameter `hosp=n` den Aufruf der API abzuschalten. Dann geht der Rest wieder

**Comment by kurtfahrrad** [comment]
Wir nutzen auch immer noch Fax…

**Comment by marcusraitner** [comment]
Mittlerweile behoben.
