### ISSUE TITLE
Error line 988:63:

### ISSUE THREAD

**Issue by Toirali** [marcusraitner/COVID-19-Dashboard#104]
Hallo, danke für das tolle script. Funktioniert aber seit heute nicht mehr. 
Kommt immer einfach Fehlermeldung…Error on line 988:63:  Type Error…
Sorry, habe leider keine Ahnung vom programmieren, bin nur User 😅
VG Thomas M. 

![69D1B6F8-33A5-4E81-8DBA-ADC454A3C620](https://user-images.githubusercontent.com/98904095/152202107-31adbfed-6e64-4068-accf-53608c605566.jpeg)

**Comment by marcusraitner** [comment]
Danke. Ist ein Problem in der API bzw. beim RKI; s. https://github.com/marcusraitner/COVID-19-Dashboard/issues/103 

Kurzfassung: einfach mit Parameter `hosp=n` temporär umgehen.

**Comment by Toirali** [comment]
Oh, danke für die schnelle Antwort! 👏💪
