### ISSUE TITLE
Error: Die Daten konnten nicht gelesen werden, da sie nicht das korrekte Format haben.   ?

### ISSUE THREAD

**Issue by eddy-tec** [marcusraitner/COVID-19-Dashboard#105]
![image](https://user-images.githubusercontent.com/97383047/154343250-ab5894be-f040-47e5-8a69-55043b464300.jpeg)

**Comment by marcusraitner** [comment]
Das RKI hat mal wieder am Excel gespielt https://github.com/marlon360/rki-covid-api/issues/399

**Comment by lululasse** [comment]
Die Excel scheint immer noch kaputt zu sein?

**Comment by marcusraitner** [comment]
Muss ich mir noch genauer ansehen, aber einstweilen hilft es `de=n` zu setzen. Da scheint das Problem zu liegen.

**Comment by Toirali** [comment]
Funktioniert trotzdem nicht ☹️

**Comment by marcusraitner** [comment]
Stimmt. Es muss auch noch `hosp=n` sein.

**Comment by Toirali** [comment]
Funktioniert trotzdem nicht ☹️

**Comment by sebster6** [comment]
Bei mir geht‘s (habe noch eine feste Location in den Parametern).

**Comment by lululasse** [comment]
Beim mir geht es mit de=n und hosp=n. Aber die Daten fehlen dann eben. Schaust Du Dir die API's nochmal an?

**Comment by lululasse** [comment]
> Beim mir geht es mit de=n und hosp=n. Aber die Daten fehlen dann eben. Schaust Du Dir die API's nochmal an?

https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/

**Comment by marcusraitner** [comment]
> > Beim mir geht es mit de=n und hosp=n. Aber die Daten fehlen dann eben. Schaust Du Dir die API's nochmal an?
> 
> https://arcgis.esri.de/aenderung-des-rki-covid-19-datensatzes/

Logisch schaue ich mir das nochmal an.

**Comment by marcusraitner** [comment]
Nur kommt beides über die https://api.corona-zahlen.org/. Sobald das dort angepasst ist, geht es im Widget automatisch wieder.

**Comment by Toirali** [comment]
Okay danke dann gehts wieder, außer Dt. Inzidenz!

**Comment by lululasse** [comment]
Geht wieder alles! Wie neu 😂! Danke!

**Comment by marcusraitner** [comment]
Nicht mein Verdienst. Das machen die Kollegen bei https://api.corona-zahlen.org/
