### ISSUE TITLE
Fehler im Script: vaccData.data.states

### ISSUE THREAD

**Issue by dsseb** [marcusraitner/COVID-19-Dashboard#106]
2022-04-29 10:09:58: Error on line 615:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states')

**Comment by marcusraitner** [comment]
Das ist ein Fehler in der API: https://github.com/marlon360/rki-covid-api/issues/427 bzw. der Praktikant hat mal wieder im Excel beim RIK rumgespielt

**Comment by Rubber1Duck** [comment]
na so massiv wie die Änderungen sind wird es nicht der Praktikant gewesen sein :-)

**Comment by marcusraitner** [comment]
Der Skandal ist auch weniger "der Praktikant" sondern eine vorsintflutliche Dateninfrastruktur beim RKI, aber Lauterbach hat dafür ja kein Geld …

**Comment by SpeedmaxX** [comment]
Gleiches Problem (natürlich), warum bleiben die Apis nicht stabil? Sowas nervt …

**Comment by marcusraitner** [comment]
Die API des RKI ist ein Excel-File … und dessen Format ändert sich immer wieder mal. Deutschland im 21. Jahrhundert

**Comment by Rubber1Duck** [comment]
> Der Skandal ist auch weniger "der Praktikant" sondern eine vorsintflutliche Dateninfrastruktur beim RKI, aber Lauterbach hat dafür ja kein Geld …

na ja ganz so vorsintflulich wie du es darstellst sind sie nun nicht. Marlons API hat das Excelfile der einfach halt halber verwendet. Dieses Excelfile ist ein Extract der csv Dateien wie sie auf github zur Verfügung stehen, und diese haben sich nicht geändert!
Wir werden nun auf diese Daten  von github umstellen (auch um die Struktur der Api zu behalten, denn das gibt das Excel File nicht mehr alles her!) und dann ist hoffendlich Ruhe ...
dauert aber ein bischen, hoffe es dieses Wochenende fertig zu stellen ............. ist in Arbeit

**Comment by marcusraitner** [comment]
Danke dir jedenfalls für die Mühe. Ein stabiles CSV ist schon mal besser, aber eigentlich auch nicht 21. Jahrhundert …

**Comment by permaMonk** [comment]
Endlich dieses issue gefunden. Schließe mich mal hier an mit meinem Fehlerbild (leicht anders):
Error on line 616:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states').
Hoffe dann auf nen Update.

**Comment by marcusraitner** [comment]
Und bis dahin einfach mit `vac=n` abschalten

**Comment by permaMonk** [comment]
Jo. Danke. Das hilft erstmal.

**Comment by lululasse** [comment]
Immer noch Error 🙄

**Comment by marcusraitner** [comment]
Solange die API nicht angepasst ist, wird sich das auch nicht ändern. Bitte einstweilen `vac=n` setzen.

**Comment by c-m0s** [comment]
> Solange die API nicht angepasst ist, wird sich das auch nicht ändern. Bitte einstweilen `vac=n` setzen.

Danke für den Workaround Tipp, aber wo muss denn `vac=n` ungefähr hin?

**Comment by permaMonk** [comment]
Lange auf das Widget drücken.

„Scriptable bearbeiten“

Unten ganz rechts nach den Geodaten durch Semikolon getrennt ohne Leerzeichen vac=n

**Comment by SpeedmaxX** [comment]
Oder 
`// Toggle showing of vaccination status
var showVaccination = false; `

**Comment by marcusraitner** [comment]
Danke für die Hilfe an allen. `vac=n` bei den Parametern des Widgets auf dem Homebildschirm (lang drücken > Widget bearbeiten). Oder wie geschrieben: direkt im Code …

**Comment by Toirali** [comment]
Vielen Dank immer gleich auf die Reaktionen, wenn was nicht funktioniert und die Anweisungen wie man was beheben kann! Toller Support! Beste Grüße T. Müller

**Comment by Rubber1Duck** [comment]
PR ist erledigt, und sollte in ein paar Minuten live sein!

**Comment by permaMonk** [comment]
PR?

**Comment by Rubber1Duck** [comment]
PR = Pull Request und der bezieht sich auf die hier verwendete API. Es sollte also auch hier wieder alles funktionieren!

**Comment by marcusraitner** [comment]
PR = Pull Request. Muss man nicht verstehen, wenn man selbst keine Software entwickelt. Soll heißen: Geht bald wieder.

**Comment by marcusraitner** [comment]
Funktioniert wieder! Einen Kaffee für @Rubber1Duck. Danke!

**Comment by marcusraitner** [comment]
Und: die Daten passen jetzt; wir hatten zeitweise mehr Zweitgeimpfte (75%) als Erstgeimpfte (74%). Jetzt ist beides 75%

**Comment by permaMonk** [comment]
Sorry Stehe aufm Schlauch heute. Public Relations, Pre Release, 🤦🏼‍♂️
Pull Request natürlich
