### ISSUE TITLE
vaccData.data.state undefined is not an object.

### ISSUE THREAD

**Issue by icsAT** [marcusraitner/COVID-19-Dashboard#108]
![image](https://user-images.githubusercontent.com/74063738/166400807-c4116dc1-1851-4148-a8e9-2194df0cc746.jpeg)

Leider scheint die von Dir verwendete API heute Morgen erneut Schwierigkeiten mit dem Impfquoten zu haben.

**Comment by marcusraitner** [comment]
Danke, ich schreibe den Kollegen

**Comment by marcusraitner** [comment]
Hast du ja schon https://github.com/marlon360/rki-covid-api/issues/431

**Comment by icsAT** [comment]
Ist schon erledigt. Sollte gleich wieder funktionieren.

**Comment by icsAT** [comment]
Schon lange erledigt.
