### ISSUE TITLE
Widget Shows nothing

### ISSUE THREAD

**Issue by maximus210793** [marcusraitner/COVID-19-Dashboard#109]
Hi, 
My widget looks like that, i am using the latest version with the following parameters:
loc=48.1385340,11.5763994;de=y;theme=rki

Looking forward to your response.
Thanks in advance. 
![04EF7B0C-3300-459F-964B-7F146B011347](https://user-images.githubusercontent.com/76915579/168600962-84b9a4d1-9a5b-4e8a-91d4-1b923d57c5cb.jpeg)

**Comment by icsAT** [comment]
Hi,

what kind of device are you using? Are you using shortcuts (maybe in addition with scriptable) on that device?
What happens if you start the script out of the scriptable app?

**Comment by maximus210793** [comment]
Using iPhone 12 with the latest iOS and no shortcuts. When I start within scriptable without parameters I get the following view. ![image](https://user-images.githubusercontent.com/76915579/168606820-08f688a3-3355-46e8-8a1e-25272e065781.jpeg)

I am currently in Austria...

**Comment by eddy-tec** [comment]
MOiN bei mir geht auch nichts...
Keine Fehlermeldung oder so...
![image](https://user-images.githubusercontent.com/97383047/168608978-c352f7f1-d7d3-4ee1-b877-f5144f0363ea.jpeg)

**Comment by Fran71** [comment]
liegt wohl an der Hospitalisierungsinzidenz der Bundesländer, in meinem Fall Bayern

"undefined is not an object (evaluating 'hospitalizationData.data[bundesLand]')

**Comment by maximus210793** [comment]
Bei mir geht weder Bayern noch baden Württemberg mit Parameter:

loc=47.6559476,9.4889567;de=y;theme=rki

**Comment by icsAT** [comment]
![image](https://user-images.githubusercontent.com/74063738/168629691-eddc9cde-21c0-4c2d-bc4f-13e1cfc08d5f.png)

Es sieht für mich so aus, als hätte die verwendete API ein Problem. Sie liefert eine Fehlermeldung.

Die Information erhalte ich, wenn showGermanValue auf false setze. Setze ich es auf true beendet sich die Scriptable App.

**Comment by icsAT** [comment]
Es gibt bereits ein Ticket dazu. Also einfach etwas abwarten.

https://github.com/marlon360/rki-covid-api/issues/436

**Comment by marcusraitner** [comment]
Thanks to all of you debugging the issue and tracing it back to the API. Meanwhile just set `hosp=n;de=n` to avoid the call to this particular API

**Comment by maximus210793** [comment]
You mean maintaining those as parameters ?

**Comment by marcusraitner** [comment]
> You mean maintaining those as parameters ?

Yes, exactly.

**Comment by maximus210793** [comment]
Still not working, those are my parameters now:
hosp=n;de=n;loc=48.1385340,11.5763994;de=y;theme=rki

**Comment by icsAT** [comment]
remove de=y

**Comment by maximus210793** [comment]
Working now thanks. When do you think the issue of my unit  initial post will be fixed approximately ? Thanks

**Comment by icsAT** [comment]
Usually they are working fast. About an hour ago they postet that they are working on it. 
I am confident that they will fix it by tomorrow, but if you need something reliable you need to ask them yourself.

https://github.com/marlon360/rki-covid-api/issues/436

**Comment by marcusraitner** [comment]
For me it's working again; API is fixed

**Comment by maximus210793** [comment]
Working again - thanks all :)
