### ISSUE TITLE
Freie Betten

### ISSUE THREAD

**Issue by josuabarron** [marcusraitner/COVID-19-Dashboard#11]
![](https://user-images.githubusercontent.com/64215210/118551258-02fee480-b75e-11eb-9dac-7c5b50163a5b.jpeg)

Freie Betten überlagern die vorhandenen Betten

**Comment by marcusraitner** [comment]
Danke. Damit hatte ich nicht gerechnet. Den umgekehrten Fall von vielen C19 Betten hatte ich aber schon abgefangen und insofern lässt sich das in gleicher Weise beheben.
