### ISSUE TITLE
Inzidenz D lässt Widget abstürzen

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#110]
Offensichtlich hat sich bei der API für die Inzidenz für ganz Deutschland wieder etwas geändert. Bei DE=y stürzt das Widget ab oder zeigt nichts mehr an.

**Comment by nils-mac** [comment]
Hat wahrscheinlich was mit dem R-Wert zu tun.

**Comment by marcusraitner** [comment]
Siehe https://github.com/marlon360/rki-covid-api/issues/440

**Comment by lululasse** [comment]
Geht scheinbar wieder! Immer noch das beste COVID Widget überhaupt!

**Comment by marcusraitner** [comment]
Vielen Dank 😊 ich wäre glücklich, wenn wir es endlich nicht mehr benötigen würden.
