### ISSUE TITLE
Probleme mit Werten für Deutschland und der Hospitalisierung.

### ISSUE THREAD

**Issue by icsAT** [marcusraitner/COVID-19-Dashboard#111]
Moin Marcus (@marcusraitner),

Marlons API liefert aktuell erneut Fehler, was zur Fehlermeldung bzw. zum Absturz Deines Skriptes führt. 

![image](https://user-images.githubusercontent.com/74063738/172039251-84b1a666-fff0-4a65-a6ee-ead7535bd639.jpeg)

Als Workaround kann man die Werte für Deutschland und Hospitalisierung deaktivieren, dann läuft es bei mir wieder.

![image](https://user-images.githubusercontent.com/74063738/172039432-97cdfffe-5523-4a45-8e9a-d1ae34c45983.jpeg)

[Issue bei Marlon ist eröffnet](https://github.com/marlon360/rki-covid-api/issues/444)

Danke für Dein tolles Widget und schöne Pfingsttage. 

Gruß André

**Comment by marcusraitner** [comment]
Danke, André! Man kann die Option auch als Parameter des Widgets setzen mit `de=n` und `hosp=n` (mehrere Optionen werden mit Semikolon getrennt). Wenn das mit Corona noch länger geht (was ich nicht glaube) dann baue ich mal ein vernünftiges Fehlerhandling ein …

**Comment by icsAT** [comment]
Läuft wieder. Ich wäre da mit meiner Einschätzung etwas vorsichtiger aber just my 50 cent.
