### ISSUE TITLE
Erneut Probleme mit der API.

### ISSUE THREAD

**Issue by icsAT** [marcusraitner/COVID-19-Dashboard#112]
Nur zur Info. Gibt erneut Probleme mit de=y.
Hab schon wieder ein Ticket eröffnet, aber gehe davon aus, dass es sich sonst morgen auch von alleine regelt. [marlon360/#445](https://github.com/marlon360/rki-covid-api/issues/445)

Gruß André

**Comment by Rubber1Duck** [comment]
In der Tat waren Deutschland weit 0 neue Fälle noch nicht vorgesehen :-) PR ist gemacht, marlon muss noch reviewen ...

**Comment by marcusraitner** [comment]
Danke euch! Auf Landkreisebene sehe ich oft am Wochenende 0 Fälle…

**Comment by icsAT** [comment]
Läuft übrigens wieder.
