### ISSUE TITLE
Fehler im Code

### ISSUE THREAD

**Issue by jseegger** [marcusraitner/COVID-19-Dashboard#113]
Hallo,

im aktuellen Code wird die Variable 'debug' nicht definiert (Zeile 35) und es kommt eine Fehlermeldung beim Ausführen. 

const debug = false;

Hab jetzt auch ne Weile gebraucht bis ich drauf gekommen bin ;-)

**Comment by marcusraitner** [comment]
Danke! Eigentlich wollte ich nur meine lokale Zeile `debug = true` nicht committen, aber irgendwie bin ich ein wenig aus der Übung ;-)
