### ISSUE TITLE
Inzidenz D bringt das Widget zum Absturz

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#114]
Bei d=y stützt das Widget mal wieder ab. API Probleme und einfach mal wieder Geduld haben und de=n einstellen oder gibt es ein anderes Problem?

Übrigens vielen Dank für die Version 1.12! Super!

**Comment by marcusraitner** [comment]
Danke für das Feedback. Die zweite Boosterimpfung war recht trivial einzubinden … im Moment gibt es ein Problem mit der API https://github.com/marlon360/rki-covid-api/issues/447

**Comment by marcusraitner** [comment]
Irgendwann baue ich wirklich ein richtiges Fehlerhandling … das geht schneller als auf Professionalität beim RKI zu hoffen

**Comment by marcusraitner** [comment]
API funktioniert wieder
