### ISSUE TITLE
API abgestürzt

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#115]
Hi Marcus,

bei de=y und hosp=y stürzt das Widget mal wieder ab. Warten auf Korrektur der API oder haben wir ein anderes Problem?

Sonnige Grüße!

**Comment by marcusraitner** [comment]
Danke! Sonnige Grüße zurück. Problem liegt an der API https://github.com/marlon360/rki-covid-api/issues/457

**Comment by Toirali** [comment]
Auch bei mir die letzten 2 Tage Fehler…
![6FBFD1C4-7C98-441A-85C3-2E0C811975DD](https://user-images.githubusercontent.com/98904095/183298663-35b27fc7-3406-4140-b16a-e65df54ade12.jpeg)

**Comment by marcusraitner** [comment]
@Toirali das ist aber was anderes. Gibst du die Koordinaten mit oder werden die automatisch ermittelt?

**Comment by Toirali** [comment]
Hallo,Ich habe die Koordinaten per Hand eingegeben loc=50.49,12.13  Bis jetzt hat das immer schon funktioniert. Nun wird gezeigt: keine Ergebnisse für den aktuellen Ort…VGGesendet mit der WEB.DE iPhone AppAm 07.08.22 um 18:41 schrieb Marcus Raitner
                
            
            
                
                    Von: "Marcus Raitner" ***@***.***>Datum: 7. August 2022An: "marcusraitner/COVID-19-Dashboard" ***@***.***>Cc: "Mention" ***@***.***>,"Toirali" ***@***.***>Betreff: Re: [marcusraitner/COVID-19-Dashboard] API abgestürzt (Issue #115)
                
                
@Toirali das ist aber was anderes. Gibst du die Koordinaten mit oder werden die automatisch ermittelt?

**Comment by marcusraitner** [comment]
@Toirali Bei mir funktionieren deine Koordinaten. Ich vermute, dass du in dem Parameter-String noch was anderes drin hast, das dann ein Problem verursacht.

**Comment by Toirali** [comment]
Lieber Herr Raitner,Hab jetzt alles aus den Parametern raus, außer den Koordinaten. Funktioniert trotzdem nicht…VGGesendet mit der WEB.DE iPhone AppAm 08.08.22 um 06:44 schrieb Marcus Raitner
                
            
            
                
                    Von: "Marcus Raitner" ***@***.***>Datum: 8. August 2022An: "marcusraitner/COVID-19-Dashboard" ***@***.***>Cc: "Mention" ***@***.***>,"Toirali" ***@***.***>Betreff: Re: [marcusraitner/COVID-19-Dashboard] API abgestürzt (Issue #115)
                
                
@Toirali Bei mir funktionieren deine Koordinaten. Ich vermute, dass du in dem Parameter-String noch was anderes drin hast, das dann ein Problem verursacht.

**Comment by marcusraitner** [comment]
Hmm 🤔 wir haben ja zwei Fehler hier. Der Parameter-String: `loc=50.49,12.13;de=n;hosp=n` funktioniert bei mir.

**Comment by kennymc-c** [comment]
Bei mir kommt es mit hosp=y zu diesem Fehler:
![image](https://user-images.githubusercontent.com/14995555/183888686-c8e15d31-7b4b-4e6c-a837-343b8256ea6b.jpeg)

Mit de=y lädt das Widget gar nicht mehr

**Comment by marcusraitner** [comment]
@kennymc-c Ja, das ist noch immer dasselbe Problem mit der verwendeten API. Im Moment hilft nur `hosp=n;de=n`

**Comment by lululasse** [comment]
Hallo Marcus, leider verstehe ich im Thread zu dem Thema bei marlon360 nur Bahnhof. 
Wie siehst Du das? Gibt es Hoffnung man kann die Schnittstelle wieder reparieren und Dein Widget läuft wieder komplett sauber durch?
Gruß lululasse

**Comment by marcusraitner** [comment]
@lululasse Das Problem ist dieses Mal anders gelagert – nicht einfach nur der Praktikant der das Excel verbogen hat. Es scheint so, als würde der Aufruf geblockt. Die Kollegen suchen gerade nach einem anderen Weg an die Zahlen zu kommen. Wenn das gelingt, kommen sie wieder normal über die API.

**Comment by lululasse** [comment]
marlon360 hat die API wieder gefixt. Es tut wieder 😀

**Comment by marcusraitner** [comment]
Großartig!

**Comment by Toirali** [comment]
Vielen Dank! Nun funktioniert’s wieder! Danke für den tollen Support! 👋Hab ich wohl was falsch eingegeben…?!Gesendet mit der WEB.DE iPhone AppAm 08.08.22 um 08:44 schrieb Marcus Raitner
                
            
            
                
                    Von: "Marcus Raitner" ***@***.***>Datum: 8. August 2022An: "marcusraitner/COVID-19-Dashboard" ***@***.***>Cc: "Mention" ***@***.***>,"Toirali" ***@***.***>Betreff: Re: [marcusraitner/COVID-19-Dashboard] API abgestürzt (Issue #115)
                
                

Hmm 🤔 wir haben ja zwei Fehler hier. Der Parameter-String: loc=50.49,12.13;de=n;hosp=n funktioniert bei mir.

**Comment by marcusraitner** [comment]
Freut mich! Danke.
