### ISSUE TITLE
Error “vaccData.data.states”

### ISSUE THREAD

**Issue by permaMonk** [marcusraitner/COVID-19-Dashboard#116]
Mal wieder ein Fehler in der RKI Excel Tabelle?

Error on line 616:48: TypeError: undefined
is not an object (evaluating
'vaccData.data.states")

Kann man nix machen? Abwarten . . .

**Comment by LeonEck** [comment]
Du kannst die Datenquellen die aktuell nicht gehen abschalten: `vac=n;de=n`

Bei der API wurden die Fehler schon gemeldet: https://github.com/marlon360/rki-covid-api/issues/465

**Comment by marcusraitner** [comment]
Danke @LeonEck für den Workaround (bin langsam weil im Urlaub) und danke an @permaMonk für's Melden. Ja, mal wieder das Datenformat / der Praktikant 😂 Das ist alles so traurig …

**Comment by permaMonk** [comment]
Danke euch beiden @LeonEck @marcusraitner für die schnelle Rückmeldung. Aber Abschalten der Datenquellen lasse ich erst mal und hoffe auf baldigen Fix von der RKI Seite.

Btw: Ich befürchte es ist nicht der Praktikant. Der ist wahrscheinlich die Person, die davon noch am meisten Ahnung hat. So oft wie das passiert.

**Comment by marcusraitner** [comment]
Stimmt. Nach zwei Jahren Datenschlamperei vom Feinsten ist das Problem nicht der Praktikant …

**Comment by marcusraitner** [comment]
Bei mir geht es wieder

**Comment by permaMonk** [comment]
Bei mir auch. Alles. Schon etwas länger. Sorry für die verspätete Rückmeldung.
