### ISSUE TITLE
Exception Occurred

### ISSUE THREAD

**Issue by RuhrmannS** [marcusraitner/COVID-19-Dashboard#117]
Leider wird seit einigen Tagen nur noch folgender Fehler ausgegeben:
Exception Occurred
Error: Ungültige URL

Besteht noch Hoffnung auf Reparatur?

Ciao
Stephan

**Comment by marcusraitner** [comment]
Interessant. Bei mir geht es nämlich. Welche Config-Parameter verwendest du denn?

**Comment by RuhrmannS** [comment]
Nur de=y

Problem erkannt (pihole) aber noch nicht gelöst...da hat wohl irgendeine Blockliste etwas zuviel getan

**Comment by marcusraitner** [comment]
Ah, ok. Dann liegt es also nicht am Skript.

**Comment by RuhrmannS** [comment]
Nope, alles gut!

Mach mich mal auf die Suche in den Listen....rki.de ist schonmal nicht geblockt....

**Comment by marcusraitner** [comment]
Die ganzen URLs stehen am Anfang des Skripts.

**Comment by RuhrmannS** [comment]
Danke für den Tip...nach dem Frühstück dann ;)

**Comment by RuhrmannS** [comment]
Match found in https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist:
  api.corona-zahlen.org

Das ist der Übeltäter, Ausnahme für "api.corona-zahlen.org" definiert und es geht wieder.

Vielen Dank für den blitzschnellen sonntagsmorgendlichen Support!

**Comment by marcusraitner** [comment]
Sehr gerne! Und ich habe wieder was gelernt (pihole)
