### ISSUE TITLE
Daten konnten nicht gelesen werden…

### ISSUE THREAD

**Issue by Toirali** [marcusraitner/COVID-19-Dashboard#118]
Seit heute…
![BDB5E36D-5BB0-4AE9-9ECF-0A8AA35197B8](https://user-images.githubusercontent.com/98904095/204138984-8d88dcfb-ae21-4150-ba47-d724aa0042c8.jpeg)

**Comment by marcusraitner** [comment]
Liegt an `https://api.corona-zahlen.org/vaccinations`; liefert derzeit einen Gateway-Fehler. Sollte hoffentlich vorbeigehen. Einstweilen einfach mit `vacc=n` ausblenden.

**Comment by thospe** [comment]
Tippfehler: Zum ausblenden muss vac=n angegeben werden

**Comment by marcusraitner** [comment]
Danke, mein Fehler. Sollte es besser wissen 😉

**Comment by Fran71** [comment]
Funktioniert wieder einwandfrei

**Comment by marcusraitner** [comment]
Danke
