### ISSUE TITLE
Keine Anzeige/Daten mehr

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#119]
Seit 1.3. funktioniert das Widget nicht mehr. Hat die Datenquelle ein Problem (wieder mal) oder ist der Service jetzt abgeschaltet worden?

**Comment by marcusraitner** [comment]
Mal wieder das API vom RKI https://github.com/marlon360/rki-covid-api/issues/504

**Comment by marcusraitner** [comment]
Mit `de=n;frozen=n;bl=n` lässt sich das Problem umgehen.

**Comment by lululasse** [comment]
Stimmt. Also Du meinst so lange die RKI Schnittstelle spinnt? Oder schaut sich das bei denen niemand mehr an?

**Comment by marcusraitner** [comment]
Beim RKI kümmert sich seit drei Jahren keiner darum 😉 die pusten das einfach raus und teilweise einfach als Excel / CSV. Die Arbeit machen in dem Fall die Kollegen bei https://api.corona-zahlen.org/docs/ siehe den oben verlinkten Issue

**Comment by icsAT** [comment]
FYI:
[Bereitstellung der RKI Covid-19 Daten zum Download über den COVID-19 Datenhub endet](https://arcgis.esri.de/bereitstellung-der-rki-covid-19-daten-zum-download-ueber-den-covid-19-datenhub-endet/)

**Comment by Rubber1Duck** [comment]
sollte alles wieder fuktionieren!

**Comment by marcusraitner** [comment]
Danke @Rubber1Duck! Funktioniert wieder

**Comment by lululasse** [comment]
Super! Danke an alle!
