### ISSUE TITLE
Wieder mal keine Daten

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#120]
Widget zeigt wieder seit 3 Tagen keine neuen Daten. Wieder ein neues API Problem?

**Comment by marcusraitner** [comment]
Scheint so. `de=n` hilft erst Mal als Workaround.

**Comment by ragalthar** [comment]
![image](https://user-images.githubusercontent.com/82751561/233351672-d27d7ae5-4a5c-4b92-ad2c-abbbcdf99127.jpeg)

Die Fehlermeldung kommt seit heute. Ist das das gleiche Problem?

Und in welcher Zeile kann ich den Parameter de=n setzen?

**Comment by marcusraitner** [comment]
@ragalthar Ist tatsächlich ein anderes Problem, das wir jetzt mit `vac=n` umgehen können. Gesetzt wird das in den Parametern des Widgets auf dem Homescreen:

![image](https://user-images.githubusercontent.com/65543240/233416669-58b934f3-d61e-4fc9-8a77-347049a9119d.jpeg)

**Comment by lululasse** [comment]
Scheint wieder alles zu funktionieren?

**Comment by marcusraitner** [comment]
Ja, geht wieder

**Comment by lululasse** [comment]
Danke!!
