### ISSUE TITLE
Seit 12.5. wieder Probleme

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#121]
Widget hat wieder Probleme. de=n und hosp=n hilft aber es fehlen Daten. 
Was ist diesmal das Problem? Vielleicht, dass die Impfdaten nur noch 1x pro Monat geupdated werden?

**Comment by marcusraitner** [comment]
Auf den ersten Blick sehe ich hier kein Problem.

**Comment by lululasse** [comment]
Hi, ging dann 10min später wieder. 

Aber jetzt geht gar nix mehr. Auch bei n Einstellungen. Fehlermeldung Daten haben nicht das korrekte Format.

**Comment by marcusraitner** [comment]
Gerade nochmal hier ausprobiert; bei mir klappt alles … evtl. nochmal installieren?

**Comment by lululasse** [comment]
Sehr merkwürdig. Jetzt geht es auch wieder, ohne dass ich etwas verändert habe. Du hast magische Hände.

**Comment by marcusraitner** [comment]
Sehr komisch
