### ISSUE TITLE
RKI Daten wurden eingestellt, richtig? Das heißt Dein tolles Widget ist damit leider auch am Ende, oder auch Gott sei Dank!

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#122]

**Comment by marcusraitner** [comment]
Ist das so? Hatte ich gar nicht mitbekommen. Falls ja, dann hat der Spuk jetzt ein Ende ;-) Verlässliche Zahlen waren es ohnehin nie, aber bessere gab es nicht ...

**Comment by marcusraitner** [comment]
Was noch funktioniert ist `frozen=y`, dann kommen die Daten von api.corona-zahlen.org. Habe aber keine Ahnung, ob das länger funktioniert.

**Comment by lululasse** [comment]
Ich hatte im Radio gehört, dass die Zahlen nicht mehr aktualisiert werden. Irgendwas hat sich auch geändert aber auf der RKI Seite steht, dass die Zahlen nach wie vor weiter aktualisiert werden. Offenbar im "Pandemieradar" und im github. 
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Gesamt.html
Dein Tipp funktioniert aber auch. 
Danke für Deine Mühe!

**Comment by marcusraitner** [comment]
Es sieht ein bisschen so aus als würde die "offizielle" API die ich mit `frozen=n` verwende nicht mehr funktioniert. Mit `frozen=y` gehe ich über die API von den Kollegen bei api.corona-zahlen.org und die beziehen das aus einer anderen Quelle des RKI.
