### ISSUE TITLE
Neuer Fehler: keine Daten gefunden

### ISSUE THREAD

**Issue by ragalthar** [marcusraitner/COVID-19-Dashboard#123]
![image](https://github.com/marcusraitner/COVID-19-Dashboard/assets/82751561/b1832c3d-298c-4b1e-962b-9ae1069da9b7)

Tritt seit ca. einer Woche auf

**Comment by Panic850** [comment]
Stellen sie den Parameter "frozen=y" dann bekommen sie wieder Daten.

**Comment by marcusraitner** [comment]
Siehe auch https://github.com/marcusraitner/COVID-19-Dashboard/issues/122

tl;dr RKI hat sein API eingestellt, aber über die Kollegen bei api.corona-zahlen.org bekommt man noch die Werte. Eben mit `frozen=y`
