### ISSUE TITLE
Script läuft leider nicht

### ISSUE THREAD

**Issue by HasanISabbah** [marcusraitner/COVID-19-Dashboard#15]
Er erkennt leider nicht alle Orte

**Comment by marcusraitner** [comment]
Welcher Ort wird nicht erkannt (Koordinaten?)

**Comment by HasanISabbah** [comment]
Ich weiß es leider nicht.
Habe das Script eingelesen, aber es wird nichts im Widget angezeigt

**Comment by marcusraitner** [comment]
Hast du irgendwelche Parameter gesetzt im Widget? Falls nicht an welchem Ort bist du gerade? Und kannst du mir einen Screenshot anhängen? Evtl. fehlt bei dir auch die Erlaubnis des Zugriffs von Scriptable auf den aktuellen Ort.

**Comment by HasanISabbah** [comment]
Bin gerade im Ausland. Liegt es daran?

**Comment by marcusraitner** [comment]
Ja, definitiv! Es funktionieren nur Ort in D. Du kannst aber einen Ort deiner Wahl in D mittels Koordinaten und dem Parameter "loc" setzen.
