### ISSUE TITLE
Differenz in der Inzidenz

### ISSUE THREAD

**Issue by KaZaAnova** [marcusraitner/COVID-19-Dashboard#16]
Erstmal: Vielen Dank für die Erstellung und die Weiterentwicklung des Widgets!

Aktuell sehe ich dort immer eine Differenz zu den Zahlen die ich über andere Quellen bekomme (z. B. Dashboard münchen.de), die Quelle dafür ist aber auch das RKI.

![IMG_1477](https://user-images.githubusercontent.com/376496/118997418-f14d5500-b988-11eb-8702-5c28ceea2cb0.jpg)
![IMG_1478](https://user-images.githubusercontent.com/376496/118997429-f3171880-b988-11eb-8e47-78d3e1791fbe.jpg)
Quelle: App "Darf ich das?"

Wie kommt diese Differenz zustande?

**Comment by JDTm** [comment]
Das ist einfach an der Stelle:
Der Graph rundet - der Wert in München ist heute 46,6 => 47.

Die alten Werte sind nicht Frozen (d.h. Enthalten nicht die Nachmeldungen). Das ist aber schon in der Anpassung. Die Werte im Graphen sind somit nachträglich um die nachgemeldeten erhöht.

**Comment by marcusraitner** [comment]
Ja, einerseits ist es die Rundung. Und andererseits die Art der Berechnung. Ich berechne die Werte immer frisch aus den Fallzahlen; Nachmeldungen führen dann nachträglich zu Änderungen. Damit das nicht passiert, friert das RKI die Zahlen in ihrem Excel ein. Du kannst aber in der ganz aktuellen Version [v.1.6.0](https://github.com/marcusraitner/COVID-19-Dashboard/releases/tag/v1.6.0) mittels des Parameters "frozen=y" dir genau diese Zahlen des RKI holen (vgl. #3). Dann passt es wieder (bis auf die Rundung).

![IMG_1026](https://user-images.githubusercontent.com/65543240/118998950-2908cc80-b98a-11eb-8f2b-bd29f11bedcc.jpeg)

**Comment by marcusraitner** [comment]
Es aus meiner Sicht berechtigte Interessen für beide Sichtweisen und darum kann man das jetzt über den Parameter steuern. Mir persönlich sind die berechneten Zahlen lieber, weil sie die aktuelle Lage besser wiedergeben ohne die Nachmeldungen zu ignorieren.
