### ISSUE TITLE
Link to Corona-Rules

### ISSUE THREAD

**Issue by Fuchs-Klaus** [marcusraitner/COVID-19-Dashboard#17]
Is it possible to link the local Corona-rules of the corresponding "Bundesland" when clicking on the widget?

(Infos on corona rules: https://www.bundesregierung.de/breg-de/themen/coronavirus/corona-bundeslaender-1745198 )

**Comment by marcusraitner** [comment]
Das klingt machbar. Muss mir eigentlich nur überlegen, wo ich den Link hinterlegen soll. Am besten wohl ein neues Icon / Emoticon oben. Und natürlich wäre es besser direkt auf das Bundesland zu springen, aber auch das ist machbar.
