### ISSUE TITLE
Höhe der Balken

### ISSUE THREAD

**Issue by toddy1986** [marcusraitner/COVID-19-Dashboard#21]
Guten Morgen. Jetzt mal jammern auf ganz hohem Niveau.
Die Höhe der Balken scheint nicht immer gleich zu sein. Inzidenz sinkt von 75 auf 74, aber der Balken scheint höher zu sein. Oder der Balken des Landes spielt hier ne Rolle?

bsp. MKK (Hessen)

![AFEBD556-2526-458E-AA35-59641C0E16BD](https://user-images.githubusercontent.com/83943893/119095984-47ff7100-ba13-11eb-878a-f0b28b493e54.jpeg)

**Comment by marcusraitner** [comment]
Das ist in der Tat verwirrend in dem Fall. Der Balken vom 21.5. hat die richtige Höhe, aber das Rechteck für das Bundesland wird auf der Inzidenzhöhe des Bundeslandes außenherum gezeichnet. Und weil beide im selben Range liegen haben sie dieselbe Farbe. Hier siehst du es besser: 

![IMG_1027](https://user-images.githubusercontent.com/65543240/119096233-9c0a5580-ba13-11eb-9436-676125a2c6b3.jpeg)

Ist also streng genommen kein Bug, sondern ein Feature. Aber wenn du eine Idee hast, wie man das verbessern könnte, her damit.

**Comment by marcusraitner** [comment]
By the way @toddy1986: Mit welchem Programm hast du deinen Screenshot bearbeitet? Das mit der Lupe ist cool und könnte ich bestimmt mal brauchen.

**Comment by toddy1986** [comment]
Man könnte ja den Rahmen um das Bundesland nicht bis zum ersten Tag des Landkreises ziehen. Also analog zu DE - getrennte Balken.

Unter iOS: Bearbeiten -> oben rechts (...) -> Markieren -> Dort gibt es unter anderem die Lupe

![E4CA79E7-D1E5-4A7B-ABF3-29971BF6AC1A_1_102_o](https://user-images.githubusercontent.com/83943893/119097737-636b7b80-ba15-11eb-86fb-f3a8687a9237.jpeg)

**Comment by marcusraitner** [comment]
Danke @toddy1986: Ich bin immer wieder fasziniert, welche Bordmittel von iOS ich nicht kenne. 

Deine Idee muss ich einfach mal ausprobieren. Aber du hast schon recht, die beiden Darstellungen (Bundesland und Deutschland) sind in gewisser Weise inkonsistent.

**Comment by marcusraitner** [comment]
Müsste mit dem aktuellen Stand jetzt funktionieren.

**Comment by torretx** [comment]
![image](https://user-images.githubusercontent.com/84558274/119258681-0ca7a280-bbcb-11eb-994a-1efa5b881c59.jpeg)

Ich würde es gut finden wenn:

1: der Rahmen um den letzten Tag verschwindet 
2: der Hintergrund wie bei den anderen vorherigen Tagen wird am aktuellen Tag
3: nur um das Bundesland ein Rahmen gezogen wird der eben nicht den aktuellen Tag mit einrahmt 
4: das Baustellen Logo verschwindet und dafür die aktuellen Corona Richtlinien durch einen Klick auf das Virus Symbol ganz links aufgerufen werden. Finde das Baustellen Logo irgendwie fehl am Platz.

**Comment by marcusraitner** [comment]
Gute Idee. an 1-3 arbeite ich gerade (allerdings tendiere ich gerade dazu aus dem Rahmen um das Bundesland und um DE eher nur zwei farbige Striche oben und unten zu machen, bin mir aber noch nicht sicher. 4. ist eine gute Idee, weil erklären muss ich den Link / das Symbol ja ohnehin.

**Comment by marcusraitner** [comment]
Sieht jetzt meiner Meinung nach besser aus.

**Comment by toddy1986** [comment]
Mir gefällt es.

**Comment by torretx** [comment]
Ja viel besser so!
