### ISSUE TITLE
Wenn null, dann kann beatmet wegfallen

### ISSUE THREAD

**Issue by 1rNidiD** [marcusraitner/COVID-19-Dashboard#22]
![image](https://user-images.githubusercontent.com/47744797/119100803-9e22e300-ba18-11eb-90d2-72231ebc2c10.jpeg)

Danke für das tolle Widget erstmal.

Als keine Schönheitsoperation könnte die Anzeige der Beatmeten COVID Patienten wegfallen, wenn eh keine COVID-Patienten auf der Intensivstation liegen. 

Soll nur ne Idee sein, ist jetzt nicht mega wichtig 😄

Danke und ein schönes Wochenende.

Didi

**Comment by marcusraitner** [comment]
Danke, Didi! Meinst du den Text oder den Balken oder beides?

**Comment by 1rNidiD** [comment]
Ich meine nur des in der Runden Klammer. C19: 0 **(davon 0 beatmet)** 
Ist ja quasi überflüssig wenn eh kein Patient auf der Intensivstation ist :)

**Comment by marcusraitner** [comment]
Ok, das sollte einfach sein. Schau ich mir an.

**Comment by 1rNidiD** [comment]
Cool danke 💪🏻
