### ISSUE TITLE
Nachkomma stelle anzeigen. 

### ISSUE THREAD

**Issue by torretx** [marcusraitner/COVID-19-Dashboard#24]
Da einige Regionen nun an diversen Schwellen sind (50 & 100) wäre es toll wenn die App eine nachkomma stelle anzeigen würde. 

Bei mir z.b sind wir heute auf 49,7 das Widget zeigt aber 50 an. Da ein Landkreis mehrere Tage unter 50 sein muss damit Lockerungen greifen, wäre die Anzeige kontraproduktiv im Widget. 

Oder man verzichtet auf das runden und lässt einfach die nachkomma stelle weg.

**Comment by marcusraitner** [comment]
Ja, da gebe ich dir recht. Kommastelle ist nicht so einfach, weil zu wenig Platz, aber Abrunden wäre sicher eine Variante, die mehr Sinn macht als das heutige Verhalten.

**Comment by Drail0r** [comment]
Moin,
eine Idee: du könntest eventuell den Impfstatus etwas schmaler machen, dort die Nachkommastelle entfernen und die Schriftgröße verkleinern und könntest so Pixel gewinnen und zumindest den aktuellen Tag, das Bundesland und Deutschland mit einer Nachkommastelle darstellen lassen. Fände ich zumindest schöner, als mathematisch inkorrekt abzurunden.

**Comment by marcusraitner** [comment]
> Moin,
> 
> eine Idee: du könntest eventuell den Impfstatus etwas schmaler machen, dort die Nachkommastelle entfernen und die Schriftgröße verkleinern und könntest so Pixel gewinnen und zumindest den aktuellen Tag, das Bundesland und Deutschland mit einer Nachkommastelle darstellen lassen. Fände ich zumindest schöner, als mathematisch inkorrekt abzurunden.

Eine gute Idee. Die Nachkommastelle beim Impfen braucht es jetzt nicht mehr; das ist eher historisch so gewachsen, weil damals sehr kleine Werte. Ich schau mir das nochmals an.

**Comment by marcusraitner** [comment]
Wenn ich die Nachkommastellen anzeige, dann würde da etwa so aussehen, hätte aber zur Folge, dass man weniger Tage sieht (konkret drei Tage weniger). Sähe dann so aus:

![IMG_1031](https://user-images.githubusercontent.com/65543240/119135605-ef45cd80-ba3e-11eb-865a-1cfb9b0a7ca6.jpeg)

Evtl. sollte ich das parametrisierbar machen.

@Drail0r: Was meinst du?

**Comment by Drail0r** [comment]
Kannst du nur die letzten drei Werte, also im Bild den 20., BY und DE mit Nachkommastellen anzeigen? Oder wenn es nach der Bundesnotbremse geht, dann eben die letzten 3 Tage? Weiter zurückliegende Tage würde ich korrekt gerundet anzeigen lassen.

Achso: Parametrisierbarkeit ist immer gut!

**Comment by marcusraitner** [comment]
Lässt sich sicherlich machen, aber ich glaube, dass dann sehr inkonsistent und unruhig wirkt. Ich glaube, ich mach es lieber so und dann parametrisierbar.

**Comment by Drail0r** [comment]
Alles klar! Danke! ♥

**Comment by marcusraitner** [comment]
@Drail0r Probier' mal mit dem aktuellen Stand `decimal=y`

**Comment by Drail0r** [comment]
Funktioniert und sieht fast perfekt aus. Ich finde es optisch schöner, wenn bei runden Werten auch xx.0 dargestellt wird. Aktuell wird dort nur die Zahl ohne Komma und Nachkommastellen angezeigt.

**Comment by marcusraitner** [comment]
Guter Punkt. Jetzt sollte es passen.

**Comment by Drail0r** [comment]
Gute Arbeit! Vielen Dank! <3
