### ISSUE TITLE
Rahmen um Bundesland anpassen 

### ISSUE THREAD

**Issue by torretx** [marcusraitner/COVID-19-Dashboard#27]
könntest du den Orangenen Rahmen um das Bundesland noch anpassen. Dieser scheint sehr weit nach links in die heutige Tages inzidenz reinzugehen. Anbei noch 2 Fotos von zwei Orten wo man es gut erkennen kann. 

![02AF1A05-26CE-4841-9636-16763712A62E](https://user-images.githubusercontent.com/84558274/119115114-18f2fa80-ba27-11eb-8d4d-a9b3642395a6.jpeg)
![76A0527C-FA57-48BF-9A97-D3DBE140CEFC](https://user-images.githubusercontent.com/84558274/119115120-1b555480-ba27-11eb-8e11-f93db6cb3760.jpeg)

**Comment by marcusraitner** [comment]
Das ist tatsächlich Absicht gewesen, um zu zeigen, dass das derselbe Tag ist bzw. dass das Bundesland den Landkreis umfasst. Nachdem das jetzt der zweite Issue dazu ist, sollte ich das auf jeden Fall ändern. Ich werde das aber bei dem ersten Issue #21 machen und diesen hier als Duplicate schließen. Bitte häng dich an #21 dran, dann bekommst du die Änderung mit.

**Comment by marcusraitner** [comment]
Duplicate of #21
