### ISSUE TITLE
München Inzidenz

### ISSUE THREAD

**Issue by hockeschisser** [marcusraitner/COVID-19-Dashboard#28]
Hallo, am 20.5. war die 7-Tage-Inzidenz in München-Stadt bei 47,6.
Warum wird das nicht angezeigt?
Mit freundlichen Grüßen

**Comment by JDTm** [comment]
Hi, hast du den Parameter Frozen=y aktiviert? Sonst sind die nachgereichten Werte mit enthalten!

**Comment by marcusraitner** [comment]
Exakt. Mit `frozen=y` passt es. Ansonsten berechne ich die Inzidenzen aus den Tageswerten und die können Nachmeldungen enthalten. Die berechnete Inzidenz ist also sozusagen realer, während die _eingefrorene_ des RKI aber die maßgebliche für Maßnahmen ist. Also: Einfach konfigurieren.

**Comment by hockeschisser** [comment]
Vielen Dank!!

 

 

Von: Marcus Raitner ***@***.***> 
Gesendet: Freitag, 21. Mai 2021 12:44
An: marcusraitner/COVID-19-Dashboard ***@***.***>
Cc: hockeschisser ***@***.***>; Author ***@***.***>
Betreff: Re: [marcusraitner/COVID-19-Dashboard] München Inzidenz (#28)

 

Exakt. Mit frozen=y passt es. Ansonsten berechne ich die Inzidenzen aus den Tageswerten und die können Nachmeldungen enthalten. Die berechnete Inzidenz ist also sozusagen realer, während die eingefrorene des RKI aber die maßgebliche für Maßnahmen ist. Also: Einfach konfigurieren.
