### ISSUE TITLE
Inzidenz mit Frozen Werten

### ISSUE THREAD

**Issue by RednUhT-0815** [marcusraitner/COVID-19-Dashboard#3]
Da alle Einschränkungen und Lockerungen sich nicht an der tatsächlichen Inzidenz des jeweiligen Tages orientieren, sondern an den frozen Werten des jeweiligen Tagen, sollten diese Zahlen angezeigt werden.
Am besten wäre es, beide per Schalter im Widget parallel nutzen zu können.

**Comment by marcusraitner** [comment]
Danke dir für die Idee. Einen Prototypen habe ich schon; Parameterhandling habe ich schon in #1 umgesetzt.
