### ISSUE TITLE
Inzidenz für Deutschland

### ISSUE THREAD

**Issue by philoupd** [marcusraitner/COVID-19-Dashboard#30]
Wenn ich de=(y) als Parameter eingebe führt das zu keiner Veränderung. Aus der Beschreibung wird mir auch nicht eindeutig klar was genau das bewirken soll. Soll lediglich der aktuelle Inzidenzwert für DE zusätzlich angezeigt werden oder sollen alle Ortsspezifischen Inzidenzwerte durch die für DE ersetzt werden?
Hilfreich wäre auch wenn sich alle werte auf DE setzen ließen.

**Comment by marcusraitner** [comment]
Hast du mal `de=y` (also ohne die Klammer probiert). Das zeigt dir aber bloß den aktuellen Inzidenzwert für DE an.

**Comment by philoupd** [comment]
Tadaaa. Ohne Klammern werden mir jetzt auch die aktuellen de Werte angezeigt :)

**Comment by marcusraitner** [comment]
Dann mache ich den Issue zu. Dein zweiter (#29) ist ja noch offen.
