### ISSUE TITLE
Balken werden falsch angezeigt bei Werten über „100“.

### ISSUE THREAD

**Issue by 1rNidiD** [marcusraitner/COVID-19-Dashboard#32]
Mit dem letzten Update werden die Balken falsch angezeigt:

![image](https://user-images.githubusercontent.com/47744797/119153225-59676e00-ba51-11eb-8774-abe054bd170f.jpeg)

Eingestellt wurde: **decimal=y** .

Wenn ich das umstelle auf **decimal=n** erhalte ich folgendes:

![image](https://user-images.githubusercontent.com/47744797/119153416-874cb280-ba51-11eb-92f6-10cfa1f27275.jpeg) 

Außerdem ist beim ersten Bild zu sehen, dass der Wert heute bei 99,0 im Landkreis Miesbach ist, mit der Umstellung auf decimal=n wird abgerundet auf 98.. 

LG Didi

**Comment by marcusraitner** [comment]
Danke für den Hinweis. Das ist komisch. Insbesondere das mit 99.0 und 98. Muss ich mir ansehen.

**Comment by 1rNidiD** [comment]
Damit du es reproduzieren kannst, dass sind meine Einstellungen: _loc=47.80,11.77;de=n;rval=y;vac=y;daily=y;beds=y;rki=n;frozen=n;decimal=n_

decimal=y dann einstellen...

Danke💪🏻

**Comment by marcusraitner** [comment]
Ist klar: Ich mache erst .toFixed() und mache dann Vergleiche mit den Werten daraus. Das sind dann aber Strings … korrigiere ich später. Du kannst einfach die vorletzte Version nehmen.

**Comment by marcusraitner** [comment]
Probier's jetzt mal aus. Sollte passen.

**Comment by 1rNidiD** [comment]
Die Balken passen jetzt, perfekt danke.

Die Zahl wird immer noch von 99 auf 98 abgerundet. 


Als Vorschlag mit den Dezimalstellen könnte man ja ne if Abfrage machen ob die Zahl größer 99,9 ist, wenn das stimmt, dann wird nur der int Wert angezeigt und ansonsten der double Wert? Damit hätte man immer ausreichend Platz. :)

**Comment by marcusraitner** [comment]
Stimmt, da war ja noch ein Problem. Schau ich mir an.

**Comment by marcusraitner** [comment]
Wer kann denn an sowas denken 🧐 der Wert ist eigentlich 98,990. Wenn ich den abrunde ist es 98, was im Sinne der Unterschreitung einer Schwelle ja stimmt. Wenn ich ihn auf eine Stelle nach dem Komma runde dann ist es 99,0. Ich muss mir das mit dem abrunden nochmal überlegen …

**Comment by marcusraitner** [comment]
So wäre es besser: erst auf eine Stelle runden und dann entweder das anzeigen oder abrunden.

**Comment by 1rNidiD** [comment]
Ja gut daran kann echt keiner denken 😂

Heute ist es genauso, der Wert für Miesbach liegt bei 101, wird aber 100 angezeigt. 

Hier würde es ja einen Unterschied machen, weil somit die **100** nicht überschritten wäre. Allerdings ist bei den Regeln selbst eine Überschreitung von 0,1 ja schon zuviel. Um Öffnungen zu erhalten, muss der Wert konstant in einem Bereich sein.

Über das allgemeine Abrunde muss also nochmal nachgedacht werden...

**Comment by 1rNidiD** [comment]
Ach und was mir noch aufgefallen ist, dass ja der Punkt "." als Komma verwendet wird. Mit _Format.number(Hier die Zahl)_ sollte des glaube ich behoben werden.

**Comment by marcusraitner** [comment]
Das bringt uns zu der Frage, wie die Grenzwerte definiert sind, bzw. zu welchem Intervall der Grenzwert selbst gehört. Ich hatte bisher so verstanden, dass ab dem Grenzwert die Schwelle als überschritten gilt, also ">=". In dem Sinn wäre Aufrunden falsch und Abrunden richtig.

**Comment by marcusraitner** [comment]
> Ach und was mir noch aufgefallen ist, dass ja der Punkt "." als Komma verwendet wird. Mit _Format.number(Hier die Zahl)_ sollte des glaube ich behoben werden.  

Danke, gute Idee!
