### ISSUE TITLE
R-Wert Anzeige fehlerhaft

### ISSUE THREAD

**Issue by cl4udiu5** [marcusraitner/COVID-19-Dashboard#35]
Der R-Wert steht bei mir (iPhone 12 Pro) vermischt mit der Inzidenz vom Bundesland ineinander und kann so nicht gelesen werden. 
Anzeige ist überlagert.

**Comment by marcusraitner** [comment]
Kannst du mir ein Bild anhängen und deine Einstellungen der Parameter schicken? Dann kann ich das nachvollziehen.

**Comment by cl4udiu5** [comment]
![0C8DC904-88DB-4D8E-B0D3-FA8FD4A5EB7D](https://user-images.githubusercontent.com/74124378/119189565-80876500-ba7c-11eb-8547-279b70d79683.jpeg)
Bild geht gerade leider nicht, weil seit dem letzten Update vor 40 Minuten das Widget kaputt ist. 

Parameter sind so: loc=48.70,9.65;de=y;rval=y;vac=y;daily=y;beds=y;rki=n;frozen=n;decimal=n

**Comment by marcusraitner** [comment]
Ok, mein Fehler. Ist gleich behoben.

**Comment by cl4udiu5** [comment]
Wenn es gleich wieder geht schicke ich ein Bild wie es bei mir mit eingeblendetem R-Wert aussieht.

**Comment by cl4udiu5** [comment]
Jetzt geht es wieder. Danke. 
So sieht das Widget bei mir mit R-Wert „Y“ aus
![C6ACEC38-BD3F-4BA3-A209-C18EBECD2BC9](https://user-images.githubusercontent.com/74124378/119190456-abbe8400-ba7d-11eb-91ca-48c52a768522.jpeg)

**Comment by marcusraitner** [comment]
Verstehe. (Habe übrigens gerade noch eine Korrektur bezüglich der Dezimalstelle nachgeschoben.)

Da lässt sich leider nicht viel machen, weil das stark von den hohen Balken links dominiert wird. Das sollte mit der Zeit besser werden.

Oder hast du eine gute Idee, was ich in dem Fall machen soll?

**Comment by cl4udiu5** [comment]
Du könntest den R-Wert in die Kopf- oder Fußzeile des Widget verschieben. Da gibt es ja noch etwas Platz dafür. 
z.B. vor das Baustellen Icon

**Comment by cl4udiu5** [comment]
Eine Anzeige der letzten Aktualisierung der Daten wäre auch noch ganz nett, wenn sich ein Platz dafür findet.

**Comment by marcusraitner** [comment]
> Du könntest den R-Wert in die Kopf- oder Fußzeile des Widget verschieben. Da gibt es ja noch etwas Platz dafür. 
> 
> z.B. vor das Baustellen Icon 

Theoretisch ja, aber dann sieht es so aus als würde sich der R-Wert auf den Landkreis beziehen, was aber ja nicht richtig ist. Darum steht er beim Inzidenzwert für DE

**Comment by marcusraitner** [comment]
> Eine Anzeige der letzten Aktualisierung der Daten wäre auch noch ganz nett, wenn sich ein Platz dafür findet. 

Eine gute Idee. Es sind aber verschiedene Datenquellen mit unterschiedlichen letzten Aktualisierungen. Vielleicht würde es aber reichen, das für die Inzidenzwerte anzuzeigen. Kannst du dafür ein neues Issue aufmachen?

**Comment by cl4udiu5** [comment]
> > Eine Anzeige der letzten Aktualisierung der Daten wäre auch noch ganz nett, wenn sich ein Platz dafür findet.
> 
> Eine gute Idee. Es sind aber verschiedene Datenquellen mit unterschiedlichen letzten Aktualisierungen. Vielleicht würde es aber reichen, das für die Inzidenzwerte anzuzeigen. Kannst du dafür ein neues Issue aufmachen?

Mach ich

**Comment by cl4udiu5** [comment]
> > Du könntest den R-Wert in die Kopf- oder Fußzeile des Widget verschieben. Da gibt es ja noch etwas Platz dafür.
> > z.B. vor das Baustellen Icon
> 
> Theoretisch ja, aber dann sieht es so aus als würde sich der R-Wert auf den Landkreis beziehen, was aber ja nicht richtig ist. Darum steht er beim Inzidenzwert für DE

Dann zeige ihn doch unter dem Kästchen für DE an. Dann sieht man, dass er dazu gehört. Vielleicht geht es ja technisch ja auch das DE Kästchen nach unten zu verlängern.

**Comment by cl4udiu5** [comment]
Jetzt sieht die Anzeige des R-Wert fast gut aus :-)
Je nach dem wie hoch oder niedrig die Inzidenz für DE ist, rutscht aber DE in R. Ich würde das R auch aus dem Kästchen nehmen und direkt darunter. 
![6A4DF902-6E19-41BA-B07C-0EC77FE98DF7](https://user-images.githubusercontent.com/74124378/119239652-d3c7e900-bb4a-11eb-8333-23bf9c96651d.jpeg)

**Comment by marcusraitner** [comment]
Danke! Ich schau mir das mal an. Kombiniere ich gleich mit #21

**Comment by marcusraitner** [comment]
Ist behoben
