### ISSUE TITLE
Rundung von Inzidenz führt zu fehlerhaften Balken

### ISSUE THREAD

**Issue by CarG70** [marcusraitner/COVID-19-Dashboard#39]
hat ein Landkreis eine Inzidenz von zB 49,7 wird im Skript auf 50 aufgerundet und der Balken wie zwischen 50 und 100 dargestellt. Die Inzidenzen sollten immer auf den kleineren vollen Wert abgerundet werde, damit der Fehler nicht auftritt.

**Comment by marcusraitner** [comment]
Das sollte aber im letzten Stand des Skripts schon so sein, also abgerundet. Ein Fehler ist aber noch drin, s. #32

**Comment by marcusraitner** [comment]
Mit dem letzten Stand hier sollte das jetzt funktionieren.
