### ISSUE TITLE
Inhalte ein/-ausblenden bzw parametisieren

### ISSUE THREAD

**Issue by youmakemyday** [marcusraitner/COVID-19-Dashboard#4]
Hallo,

es wäre toll wenn man die unterschiedlichen Inhalte wie zB Impfquoten/Bettenauslastung ausblenden könnte. Also zB nur die Inzidenzen der letzten 7 oder 14 Tage darstellen. Ich würde es gern bei älteren Herrschaften zum Einsatz bringen, die momentan von den vielen Infos etwas überfordert sind.

**Comment by marcusraitner** [comment]
Danke für die Idee! Erweitertes Parameterhandling habe ich schon via #1 implementiert.

**Comment by youmakemyday** [comment]
perfekt, vielen Dank
