### ISSUE TITLE
Frage: Fester Ort

### ISSUE THREAD

**Issue by Win002** [marcusraitner/COVID-19-Dashboard#44]
Hi,
Kann ich die Stadt Mönchengladbach fest hinterlegen?

**Comment by marcusraitner** [comment]
Klar! Das macht der Parameter `loc` des Widgets auf dem Homescreen. Einfach bei Google Maps die Koordinaten suchen und einsetzen. In deinem Fall `loc= 51.1627219,6.4288299`

**Comment by Win002** [comment]
Hallo Marcus,

vielen Dank für die schnelle Antwort.

Habe das Script jetzt auf dem Rechner geöffnet.
Könntest du mir noch die Zeile des Befehls sagen?

Grüße
Oliver Dietrich

Marcus Raitner ***@***.***> schrieb am Mo. 24. Mai 2021 um
08:04:

**Comment by marcusraitner** [comment]
Da liegt das Missverständnis. Das Widget auf dem Homescreen hat Parameter und dort kannst du das eintragen. Schau mal den [Artikel](https://www.iphone-ticker.de/covid-19-dashboard-iphone-widget-zeigt-lokale-inzidenzen-174666/) dazu. Ich sollte das wohl mal ins README nehmen.

**Comment by Win002** [comment]
Compris, ich bin restlos begeistert, wie schön man so etwas hinbekommen
kann, wenn es beherrscht😊


Marcus Raitner ***@***.***> schrieb am Mo. 24. Mai 2021 um
08:54:

**Comment by marcusraitner** [comment]
Danke! Das freut mich.
