### ISSUE TITLE
Idee zu frozen=y

### ISSUE THREAD

**Issue by toddy1986** [marcusraitner/COVID-19-Dashboard#45]
Ich bin Frühaufsteher und schaue gleich auf dein Widget. Ich habe es auf frozen=y gesetzt, um die Regeln für meinen Landkreis besser zu überwachen. Leider ist der aktuelle Tag immer erst relativ spät ersichtlich, vermutlich weil das RKI dies so spät bereit stellt. Für mich wäre es daher super, wenn alle Tage bis auf heute frozen sind und der heutige Tag aus den aktuellen Daten der API besteht. Hoffe das ist verständlich. Lg.

**Comment by marcusraitner** [comment]
Verstehe ich und hat mich selbst auch schon geärgert dieser Verzug (es lebe die Digitalisierung …). Du willst den heutigen Tag aber nur berechnen, wenn er (noch) nicht über die Schnittstelle kommt, oder?

**Comment by toddy1986** [comment]
Ja genau. Sobald die Schnittstelle den Wert bereit stellt, wäre die Berechnung ja obsolet.

**Comment by marcusraitner** [comment]
Ok, nur irgendwie müsste ich es ja dann kennzeichnen, dass der Wert noch "vorläufig" ist … müsste ich mir überlegen.

**Comment by torretx** [comment]
Apps wie darf ich das haben die zahlen auch sehr schnell und ich vermute ebenfalls, dass die Zahlen dort am aktuellen Tag gemischt werden bis die Frozen zahlen da sind. Von daher würde sicher eine Info in der Readme reichen oder? Oder einfach ein *an der Zahl solange es noch nicht die Frozen Zahl ist.

**Comment by marcusraitner** [comment]
> Apps wie darf ich das haben die zahlen auch sehr schnell und ich vermute ebenfalls, dass die Zahlen dort am aktuellen Tag gemischt werden bis die Frozen zahlen da sind. Von daher würde sicher eine Info in der Readme reichen oder? Oder einfach ein *an der Zahl solange es noch nicht die Frozen Zahl ist.

Ja, hast recht. Vermutlich reicht einfach eine Erklärung im README.
