### ISSUE TITLE
Vorschlag: Absolute Zahl der heutigen Neuinfektionen

### ISSUE THREAD

**Issue by twil1305** [marcusraitner/COVID-19-Dashboard#46]
Hallo,
wäre es noch möglich in die Balken des jeweiligen Tages die Zahl der Neuinfektionen anzugeben? Dann hätte man wirklich alle relevanten Infos auf einen Blick.

**Comment by marcusraitner** [comment]
Hi. Genau das sind doch die helleren Anteile unten in jedem Balken (wenn `frozen=n`). Oder besser gesagt: es sind die Fälle des Tages normiert auf 100.000 damit sie zur Skala der Inzidenz passen.

**Comment by twil1305** [comment]
Das hab ich schon verstanden. Aber mit den Balken kann man sich weniger vorstellen, als wenn die Infektionen noch als Zahlen ersichtlich sind.

**Comment by marcusraitner** [comment]
Ok, verstehe. Die absolute Fallzahl dort anzuzeigen wäre aber verwirrend, weil die ja höher sein kann als die Inzidenz oben (bei hoher Einwohnerzahl); dann steht unten eine höhere Zahl als oben an dem Balken.

**Comment by twil1305** [comment]
Ok, da hast du Recht. Mit den Zahlen könnte man aber dafür auch feststellen wie sich die Inzidenz entwickeln könnte. Man sieht dann immer welche Werte rausfallen bzw. rausgefallen sind.

**Comment by 1rNidiD** [comment]
Ich finde die Lösung hier eig ganz schön. Es interessiert einen ja eigentlich immer nur die aktuelle/heutige Zahl.

![image](https://user-images.githubusercontent.com/47744797/119613850-def66f80-bdfd-11eb-959a-eb6ddb596666.jpeg)

Jeder, der in einem LK mit vielen Einwohnern wohnt, weiß auch wie er die Zahl zu interpretieren hat. Also die Neuinfektionen zu integrieren, sollte kein Problem darstellen.

Was vielleicht auch eine Überlegung wäre, die offiziellen Farben der Bereiche zu nehmen. Sprich dieses rot für 50-150, dunkelrot für 150-250, lila, gelb, orange für die jeweiligen Bereiche.. 

Oder es wird einem die Möglichkeit gegeben, die Farben manuell einzustellen. 

LG Didi

**Comment by marcusraitner** [comment]
Stimmt, Didi. Mit dem + davor könnte es gehen und nur den Wert für den aktuellen Tag. Was sind denn deiner Meinung nach die "offiziellen" Farben? (Ok, ich könnte einfach im anderen Widget nachschauen …) Ich bin nicht sicher, ob es sowas wie "offiziell" gibt.

**Comment by 1rNidiD** [comment]
Die "offiziellen" Farben sind für mich die Einfärbungsfarben auf dem RKI Dashboard. 

![image](https://user-images.githubusercontent.com/47744797/119628959-defe6b80-be0d-11eb-87f5-956404160dce.jpeg)

Somit würde alles einheitlicher gehalten werden und es taugen nicht auf jeder Informationsquelle neue Farben auf. Ist aber natürlich Geschmacksache und daher auch nicht wirklich relevant. Sollte nur als kleiner Vorschlag dienen, ist aber kein Muss. Finde das Widget auch so schon richtig richtig gut! 

Finde es schon fraglich, warum so ein Feature nicht in der Warn-App integriert ist. Sollte ja eigentlich kein Problem darstellen und würde vielleicht dazu führen, dass die App mehr genutzt wird.

**Comment by marcusraitner** [comment]
Danke dir. Die Farbskala hat insofern ein Problem als dass die Stufe 165 fehlt, die ja durchaus relevant ist. Ich kann aber durchaus verschiedene Farbschemata optional anbieten; kannst du dafür ein eigenes Issue machen?

**Comment by 1rNidiD** [comment]
#49 Erstellt :)

**Comment by mirkowein** [comment]
Hi, ich plädiere dafür, +tägliche Fälle in den Balken als Zahl zu schreiben. Und zwar über den ganzen angezeigten Verlauf. 
So kann man abschätzen, wie der Verlauf in Zukunft sein wird. Durch den gleitenden Durchschnitt ist die Inzidenz ja träger.

**Comment by marcusraitner** [comment]
@mirkowein Danke. Werde ich in Kombination mit #48 ausprobieren. Vermutlich gehe ich dann aber auf eine größere Balkenbreite (so wie heute bei `decimal=y`)
