### ISSUE TITLE
Verzögerung zwischen Widget und manueller Aktualisierung?

### ISSUE THREAD

**Issue by torretx** [marcusraitner/COVID-19-Dashboard#47]
Kann es sein, dass es eine größere Verzögerung gibt zwischen der Anzeige des Widgets und der Anzeige wenn ich das Script in Scriptable manuell starte / drücke? 

Hier mal die Vergleichsfotos:

Widget:
![image](https://user-images.githubusercontent.com/84558274/119609881-9b4d3700-bdf8-11eb-9b24-af67fcf4796f.jpeg)

Scriptable:
![image](https://user-images.githubusercontent.com/84558274/119609917-ab651680-bdf8-11eb-91fd-e8b2f4e094c0.png)

**Comment by torretx** [comment]
Nachtrag, betrifft nur die Frozen werte. Werden die später zur Verfügung gestellt?

**Comment by marcusraitner** [comment]
Ja, die Frozen-Werte kommen über eine andere Schnittstelle, die erst im Laufe des Vormittags aktualisiert wird. Dazu gibt es auch schon diesen Vorschlag #45
