### ISSUE TITLE
Darstellung verschiedener Zeithorizonte

### ISSUE THREAD

**Issue by marcusraitner** [marcusraitner/COVID-19-Dashboard#48]
Als Nutzer
will ich die Details (Inzidenz, etc.) der aktuellen Tage _und_ die längere Historie gröber sehen
damit ich über die aktuelle Lage informiert bin, aber auch mehr Historie sehe

Lösungsidee: Analog hier 

![image](https://user-images.githubusercontent.com/47744797/119613850-def66f80-bdfd-11eb-959a-eb6ddb596666.jpeg)

können die Balken in der Vergangenheit ohne Beschriftung bleiben (oder ggf. nur das Monat markiert werden, aber jedenfalls ohne Inzidenzwerte) und sehr eng aneinander bleiben und nur die aktuellen ca. 7 Tage werden wie bisher dargestellt.

Anzahl der detaillierten Tage als Parameter `days` umsetzen und die Anzeige dann immer mit einer Dezimalstelle.

**Comment by 1rNidiD** [comment]
Finde ich super und äußerst interessant deine Überlegung! 
Als weiteren Schritt könnte überlegt werden, welche Regeln aktuell für die Region gelten. 

Kleines Beispiel, was vom LK Miesbach auf der Webseite vom Landratsamt bereitgestellt wird:

![image](https://user-images.githubusercontent.com/47744797/119650983-c0f03580-be24-11eb-8846-57c3855d932e.png)

Rechts ist zu sehen, wann es zu Lockerungen oder Einschränkungen kommt, es könnte im Widget ein Trend und der aktuelle Status angezeigt werden. 

Lockerrungen können ja nur erfolgen, wenn konstant ein Bereich in einem Zeitraum, eingehalten wird. 
Dies alles ist sehr unübersichtlich und verwirrend, eine Anzeige im Widget wäre ein echtes Feature und würde nochmal für Klarheit sorgen denke ich.

**Comment by marcusraitner** [comment]
Danke für den Input! Sind denn diese Zeitfenster (5 Tage Unterschreitung / 3 Tage Überschreitung) einheitlich bundesweit (sollten sie jetzt eigentlich sein). Dann ließen sich solche Fenster schon darstellen / berechnen

**Comment by 1rNidiD** [comment]
> Überschreitet die Sieben-Tage-Inzidenz an drei Tagen hintereinander die Schwelle von 100, greifen schärfere Maßnahmen. Und diese Maßnahmen gelten solange, bis die Sieben-Tage-Inzidenz an fünf aufeinanderfolgenden Werktagen die Schwelle von 100 wieder unterschreitet. Quelle: [tagesschau vom 24.04.21](https://www.tagesschau.de/inland/innenpolitik/faq-corona-notbremse-101.html)

So wie ich des auf mehreren Seiten jetzt gelesen habe, gilt die bundesweite Notbremse für alle Städte und Kreise gleich ab der 100derter Marke. Jedoch sind die Maßnahmen teilweise nochmal verschärft, was ab dieser Marke passiert. Bayern ist mit am strengsten.. 

Ich denke es ist interessant, den "Bereichs-Wert" der letzten 5 Tage dazustellen und wenn dieser an drei aufeinanderfolgenden Tagen überschritten wird, steigt der "Bereichs-Wert" an und braucht dann wieder 5 Tage, bis der Wert wieder sinken kann, um anschließend nochmal 2 Tage zu brauchen, bis die Lockerungen gültig sind (damit die 7. Tage erreicht werden). 

Welche Lockerungen/Beschränkungen dann in den jeweiligen Regionen sind, muss jeder Nutzer selber wissen.

Bei den ganzen Regeln blickt eh keiner mehr so richtig durch..

**Comment by marcusraitner** [comment]
Danke. Ja, noch zwei Jahre Pandemie und das Regelwerk ist dicker als die deutsche Steuergesetzgebung ;-) Aber die aktuellen Regeln sind wenigstens verlinkt im Titel des Widgets.

Ich probier mal was aus.

**Comment by marcusraitner** [comment]
Bringt das so in etwa einen Mehrwert? 

![IMG_1114](https://user-images.githubusercontent.com/65543240/119717378-84452e00-be66-11eb-8fee-da1de7c88a91.jpeg)

**Comment by 1rNidiD** [comment]
Wow, gefällt mir gut. Der Verlauf ist schön zu erkennen und die letzten Tage sind mit mehr Details sehr praktisch.

Wie gefällt es dir?

Als Idee würden mir folgende Punkte spontan einfallen:

![image](https://user-images.githubusercontent.com/47744797/119737939-2291bd80-be80-11eb-9c03-1709f9b1194e.jpeg)

- Verlauf über die gesamte Breite darstellen, die letzten sieben Tage mit Details. 
- Inzidenz von Land und Bund nach oben verschieben um "Platz zu machen".
- Es könnte überlegt werden, den Schriftzug **7-Tage-Inzidenz** wegzulassen. Denke jeder der das Widget verwendet, weiß was der Verlauf darstellt. 
- R-Wert vielleicht auch links oder rechts von dem Landes- und Bundeswerten darstellen.

Mehr fällt mir gerade nicht ein. Ist aber wie gesagt auch viel Geschmacksache und ich will hier auch dein Widget garnicht so stark beeinflussen 🙈 also ich finds wie gesagt eh schon sehr gut. Danke dafür.

**Comment by marcusraitner** [comment]
Danke Dir. Mir gefällt es auch gut. Danke für deine Vorschläge. Die Idee, Bundesland und DE irgendwo anders hinzuschieben, um dem Verlauf mehr Platz zu geben gefällt mir. Ich hatte es zwar bewusst dort gehabt, damit auch visuell erkennbar ist, wie sich die Werte zum Landkreis verhalten. Aber ich glaube, das ist nicht so entscheidend.

Was soll das "28" ob heißen?

**Comment by 1rNidiD** [comment]
Die 28 hatte ich nicht mehr gelöscht 🤦🏼‍♂️ hatte nur die Balken gezählt die angezeigt werden und hatte mir dazu noch überlegt, ob es vielleicht möglich ist den Verlauf von einem ganzen Monat dazustellen. Das ist aber eigentlich eher unrelevant...also die Zahl kannst ignorieren. 

Die Werte von Land und Bund haben da auch super gepasst, also warum die an dieser Stelle sind, verstehe ich voll. Ich finde es so praktisch, wie die Impfungen und die Intensivbetten dargestellt werden, so platzsparende und übersichtlich, des würde mir bei den Werten von Bund und Land auch gefallen. Wenn die quasi ihren eigen Bereich haben.

**Comment by marcusraitner** [comment]
> Die Werte von Land und Bund haben da auch super gepasst, also warum die an dieser Stelle sind, verstehe ich voll. Ich finde es so praktisch, wie die Impfungen und die Intensivbetten dargestellt werden, so platzsparende und übersichtlich, des würde mir bei den Werten von Bund und Land auch gefallen. Wenn die quasi ihren eigen Bereich haben.

Ja, verstehe. Das macht durchaus auch Sinn.

**Comment by 1rNidiD** [comment]
Eine spontane Idee wäre noch die Einführung von Achsen. 
In Y-Richtung könnte der höchste Wert des Verlaufs angezeigt werden, der Mittelwert und der kleinste Wert. Somit könnten die Balken besser eingeschätzt werden. 

In X-Richtung könnte entweder das Wochenende angezeigt werden oder vielleicht alle 3-5 Tage die Zahl des jeweiligen Tages. Somit könnten eventuell noch mehr Informationen auf einen Blick dargestellt werden. 

![image](https://user-images.githubusercontent.com/47744797/119806812-d9bf2080-bee2-11eb-83ad-241fc9bbed46.jpeg)

So vielleicht.

**Comment by marcusraitner** [comment]
Coole Idee. Danke dafür. Hatte gestern noch einen ähnlichen Impuls: Einfach den höchsten Wert noch beschriften, aber deine Idee ist besser. Wobei ich die Y-Achse dann eher mit den (relevanten / sichtbaren) Schwellwerten beschriften würde.

Muss ich ausprobieren.

**Comment by 1rNidiD** [comment]
Gerne, hört sich auch sehr gut an mit der X-Achse.

**Comment by marcusraitner** [comment]
Erster Snapshot im [Branch issue48](https://github.com/marcusraitner/COVID-19-Dashboard/tree/issue48)
