### ISSUE TITLE
Farbliche Darstellung anpassen (gem. RKI)

### ISSUE THREAD

**Issue by 1rNidiD** [marcusraitner/COVID-19-Dashboard#49]
User können die farbliche Darstellung der Balken _(oder auch des gesamten Widgets)_ selber anpassen oder vorgefertigte Varianten wählen. 

Style Optionen wären beispielsweise:

- RKI 
- black & white
- classic (wie jetzt😊)
- benutzerdefiniert

**Comment by marcusraitner** [comment]
Gute Idee. Danke.

**Comment by marcusraitner** [comment]
@1rNidiD Du darfst gerne auch ein paar Vorschläge zu den Farben machen in diesem JSON-Format: 

`[{
    lower: 0,
    color: new Color('#cccccf', 1)
  },
  {
    lower: 35,
    color: new Color('#FFBA08', 1)
  },
  {
    lower: 50,
    color: new Color('#F48C06', 1)
  },
  {
    lower: 100,
    color: new Color('#E85D04', 1)
  },
  {
    lower: 165,
    color: new Color('#DC2F02', 1)
  },
  {
    lower: 200,
    color: new Color('#9D0208', 1)
  }
];
`

**Comment by 1rNidiD** [comment]
Mache ich 💪🏻

**Comment by marcusraitner** [comment]
Danke! Kannst es ja auch in Scriptable in dem Widget selbst machen, dann siehst du auch gleich das Ergebnis. Und natürlich kannst du auch mit dem Gradienten für den Hintergrund spielen …

**Comment by toddy1986** [comment]
Weiß nicht, ob du hier schon weiter gekommen bist, würde das hier mal als RKI Schema vorschlagen:

https://coolors.co/ffffff-fcf39f-f9af4d-ff3d33-cc0a00-8c0801-f202ca


const incidenceColors = [{
    lower: 0,
    color: new Color('#ffffff', 1)
  },    
  {
    lower: 5,
    color: new Color('#fcf39f', 1)
  },
  {
    lower: 25,
    color: new Color('#f9af4d', 1)
  },
  {
    lower: 50,
    color: new Color('#ff3d33', 1)
  },
  {
    lower: 100,
    color: new Color('#cc0a00', 1)
  },
  {
    lower: 250,
    color: new Color('#8c0801', 1)
  },
  {
    lower: 500,
    color: new Color('#f202ca', 1)
  }
];

**Comment by marcusraitner** [comment]
Cool. Jetzt gibt es nur noch ein "Problemchen" die Farben für die kleinen Werte sind recht hell und ich zeichne die aktuelle Fallzahl nochmal heller drüber, das wird man dann nicht mehr sehen. Da muss ich mir noch was überlegen.

**Comment by toddy1986** [comment]
Ich muss zugeben, ich nutze nur frozen=y. Dort tritt das Problem nicht auf.

**Comment by marcusraitner** [comment]
> Ich muss zugeben, ich nutze nur frozen=y. Dort tritt das Problem nicht auf.

Dann hast du das Problem nicht. Aber auch dafür findet sich sicher eine Lösung. Ich kann ja mal verschiedene Farbschemata einbauen (als Parameter) und dann kann sich jeder das passende suchen.
