### ISSUE TITLE
Keine Aktualisierung heute

### ISSUE THREAD

**Issue by Win002** [marcusraitner/COVID-19-Dashboard#50]
Irgendwie ist man dran gewöhnt😉

**Comment by marcusraitner** [comment]
Welche Aktualisierung? Falls du mit `frozen=y` arbeitest, dann dauert das morgens immer bis der aktuelle Wert da ist (visuell fehlt dann der heutige Tag). Dazu gibt es schon dieses Issue #45

**Comment by Win002** [comment]
Ich meine keine Daten heute.

**Comment by marcusraitner** [comment]
Und deine Einstellung ist `frozen=y`? Dann ist das dieselbe Diskussion wie #45

**Comment by Win002** [comment]
Bewusst habe ich dies nicht eingestellt, da ich kein Fachmann bin. 
Ich nutze das Widget out of the Box mit deinem Tip des lokalen Ortes Loc=

**Comment by marcusraitner** [comment]
Ok, interessant. Schickst du mir mal einen Screenshot? Und deine Parameter (loc= ...)

**Comment by Win002** [comment]
Einmal Krefeld und einmal Mönchengladbach
Viele Grüße


Marcus Raitner ***@***.***> schrieb am Do. 27. Mai 2021 um
09:12:

**Comment by 1rNidiD** [comment]
![image](https://user-images.githubusercontent.com/47744797/119789098-09fec300-bed3-11eb-8825-a02d68165d73.jpeg)

Oben: loc=51.34,6.58;frozen=n

Unten: loc=51.34,6.58;frozen=y

---------------------------------------
![image](https://user-images.githubusercontent.com/47744797/119790072-ea1bcf00-bed3-11eb-9a0c-8c4b23c017d7.jpeg)

Oben: loc=51.17,6.43;frozen=n

Unten: loc=51.17,6.43;frozen=y

---------------------------------------

Sehr interessant wie unterschiedlich die Balken sind. Von welcher Berechnung hängen dann die Beschränkungen/Lockerungen ab? Das kann ja gravierende Unterschiede mit sich bringen.

**Comment by Win002** [comment]
Komisch, bei mir aktualisiert es nicht, trotz der Parameter


DidiRednit ***@***.***> schrieb am Do. 27. Mai 2021 um 10:06:

**Comment by 1rNidiD** [comment]
Ein Screenshot wäre hilfreich und welche Version des Skripts verwendet wird. 

Ich würde das aktuelle Skript als neues Skript in Skriptable hinzufügen, dann ein neues Widget erstellen und die selben Parameter einstellen. Wenn das nicht das gleiche Ergebnis (außer dem Hintergrund) wie bei mir liefert, dann müsste man sich das genauer anschauen. @Win002 

Oder ist dein Problem, dass einmal der 26.05. angezeigt wird und dann der 27.05. und du somit meinst, dass heute nichts gekommen ist?
Die Werte, die im laufe des gestrigen Tages an das RKI gemeldet wurden, sind ja die Zahlen vom Vortag. Es gibt immer einen Tag Verzug und wenn die Daten nicht rechtzeitig übermittelt werden, dann kann es passieren, dass die Daten erst am darauffolgenden Tag eingepflegt werden.

**Comment by Win002** [comment]
Das oberste ist mit deinen letzten Parametern,
Version ist 1.7
Ich habe iPhone auch neu gestartet.
Viele Grüße

DidiRednit ***@***.***> schrieb am Do. 27. Mai 2021 um 10:40:

**Comment by marcusraitner** [comment]
> Sehr interessant wie unterschiedlich die Balken sind. Von welcher Berechnung hängen dann die Beschränkungen/Lockerungen ab? Das kann ja gravierende Unterschiede mit sich bringen.

Die Maßnahmen hängen von den "offiziellen" Zahlen ab, also `frozen=y`

**Comment by marcusraitner** [comment]
@Win002 Ich verstehe noch nicht ganz, was das Problem ist. Ist es, dass der aktuellste Wert dem gestrigen Datum zugeschrieben wird? Das erkläre ich im README auch und kannst du über den Parameter `rki=y` auch ändern oder über `frozen=y`, weil das automatisch die Logik des RKI verwendet, dass der Inzidenzwert der vergangenen sieben Tage dem heutigen Tag zugeordnet wird (vielleicht sollte ich das auch immer einfach so machen und den Parameter `rki=(y|n)` ausbauen. Das verwirrt nur und bringt keinen Mehrwert.)

**Comment by Win002** [comment]
Das sind die Parameter: loc=51.34,6.58,rki=y
Auch wenn ich sie ganz rausnehme ändert sich nichts

**Comment by theadnut** [comment]
Servus,
ich weiß nicht ob er das Problem meint aber bei mir werden häufig die Daten auch nicht aktualisiert. Erst wenn ich das Script über scriptable öffne Läd er die Daten. 
mich habe keine Anpassungen bei den Parametern vorgenommen. 
![Uploading 99FDB5AF-5D40-49F3-BFC5-F57E3F33E97C.jpeg…]()

https://ibb.co/KX3jZzJ

**Comment by marcusraitner** [comment]
> Das sind die Parameter: loc=51.34,6.58,rki=y
> Auch wenn ich sie ganz rausnehme ändert sich nichts

Also bei mir sieht es mit den Parametern so aus:

![IMG_1115](https://user-images.githubusercontent.com/65543240/119805736-cd869380-bee1-11eb-8cee-ae6cb30c1d80.jpeg)

Wie sieht es bei dir aus?

**Comment by marcusraitner** [comment]
Nachtrag: Du musst die Parameter mit `;` trennen, d.h. in deinem Fall: `loc=51.34,6.58;rki=y` dann hast du alles  um einen Tag verschoben, so wie es das RKI definiert hat.

**Comment by marcusraitner** [comment]
> ich weiß nicht ob er das Problem meint aber bei mir werden häufig die Daten auch nicht aktualisiert. Erst wenn ich das Script über scriptable öffne Läd er die Daten.

Ja, das Problem gibt es auch; ist hier in #18 und #13 adressiert.

**Comment by Win002** [comment]
Mit Frozen=y hat's jetzt geklappt. Vielen Dank noch mal

**Comment by marcusraitner** [comment]
Sehr gerne!

**Comment by Win002** [comment]
Nur eine Verständnisfrage: die ganzen Tage funktionierte das Widget ganz
normal.
Seit heute nur mit Frozen=Y
Was bedeutet das?

Marcus Raitner ***@***.***> schrieb am Do. 27. Mai 2021 um
12:00:

**Comment by marcusraitner** [comment]
> Nur eine Verständnisfrage: die ganzen Tage funktionierte das Widget ganz normal. Seit heute nur mit Frozen=Y Was bedeutet das? 

Kannst du mir denn beschreiben / zeigen, was genau heute nicht normal funktioniert(e) ohne diesen Parameter? Was war anders als gestern?

**Comment by Win002** [comment]
Oben ist ohne Parameter, Stand verharrt am 26.5.  Drunter ist mit Frozen=y.
Stand ist 27.5., was ja richtig ist.
(Die ganzen letzten Tage war der letzte Tag immer mit Datum identisch, bis
auf heute.)

Marcus Raitner ***@***.***> schrieb am Do. 27. Mai 2021 um
14:19:

**Comment by marcusraitner** [comment]
> Oben ist ohne Parameter, Stand verharrt am 26.5. Drunter ist mit Frozen=y. Stand ist 27.5., was ja richtig ist. (Die ganzen letzten Tage war der letzte Tag immer mit Datum identisch, bis auf heute.)

Sehr komisch. Ich kann mir das nicht erklären. War denn optisch auch eine "Lücke" zu erkennen, also hat der heutige Tag gefehlt oder war einfach dort wo der heutige Tag steht das gestrige Datum? Wie auch immer, ich werde das vereinheitlichen müssen. Siehe #51
