### ISSUE TITLE
Beschriftung abgeschnitten 

### ISSUE THREAD

**Issue by dennerforen** [marcusraitner/COVID-19-Dashboard#6]
![65D5F811-A95A-4ECA-84B8-2F22F736A082](https://user-images.githubusercontent.com/73590285/118374751-225f0b80-b5be-11eb-9a88-827b01229b32.jpeg)

Hi, irgendwas mit der Beschriftung ist komisch. Neueste Version ist drauf.

**Comment by marcusraitner** [comment]
Danke für die Info. Das Feature hatte ich schon länger eingebaut, dass wenn mehr als die Hälfte der Betten rot sind, das Label links davon kommt, aber so war das eigentlich nicht gedacht …

**Comment by dennerforen** [comment]
Oki, manchmal kommt es unerwartet 😅

**Comment by marcusraitner** [comment]
Sollte mit [v1.5.0](https://github.com/marcusraitner/COVID-19-Dashboard/releases/tag/v1.5.0) behoben sein.

**Comment by dennerforen** [comment]
![8E327F11-6AB6-4E90-8106-AA8D25CD94C1](https://user-images.githubusercontent.com/73590285/118405343-ceb0f880-b677-11eb-897b-e8819706367c.jpeg)

danke, jetzt passt es.
