### ISSUE TITLE
Bundesland optional ausblenden

### ISSUE THREAD

**Issue by mloadschmid** [marcusraitner/COVID-19-Dashboard#61]
Für Hamburg, Bremen und Berlin wäre es sinnvoll, wenn man optional das Bundesland ausblenden könnte, um a) keine Redundanzen zu haben und b) mehr Platz für weitere Inzidenzwerte.

**Comment by marcusraitner** [comment]
Ja, das macht Sinn. Lässt sich machen.

**Comment by mloadschmid** [comment]
Super! Vielleicht ist das hier die passende Gelegenheit, um zu erwähnen, dass Dein Widget wirklich das beste Corona Widget ist, das ich kenne. Und ich habe die Entwicklungen diesbezüglich sehr aufmerksam verfolgt. 

Danke für Deine tolle Arbeit!

**Comment by Win002** [comment]
Für iOS gibt es noch „Darf ich das“ Sehr übersichtlich und schnell mit
Aktualisierungen,
allerdings nicht so schön wie Widget hier. Deshalb hatte ich das erste auch
in Scriptable Covid Schön genannt😉

mloadschmid ***@***.***> schrieb am So. 6. Juni 2021 um 14:36:

**Comment by marcusraitner** [comment]
Danke für die Blumen! Update kommt später. Sieht dann in etwa so aus:

![image](https://user-images.githubusercontent.com/65543240/120928022-4efcd380-c6e3-11eb-9765-98762117b9a3.jpeg)

Kann über `bl=(y|n)` gesteuert werden.

**Comment by mloadschmid** [comment]
Sehr gut, genau so hatte ich mir das vorgestellt.

**Comment by marcusraitner** [comment]
Viel Freude damit. Ist jetzt drin

**Comment by mloadschmid** [comment]
Danke!
