### ISSUE TITLE
Widget-Fehler!

### ISSUE THREAD

**Issue by HJE0815** [marcusraitner/COVID-19-Dashboard#62]
Hallo,
ich habe auf dem Homebildschirm das Widget 8 mal eingebunden, d.h. für meinen Landkreis und die umliegenden auch.
Leider kommt sehr, sehr häufig der Fehler "Error in line 513:48: TypeError: undefined ist not an object (evaluation 'vaccData.data.states')". Ein anderes Mal gehts dann wieder.

Bitte mal prüfen. Danke

**Comment by HJE0815** [comment]
Der Fehler kommt auch teilweise in Scriptable bei Einzelausführung auch.

**Comment by marcusraitner** [comment]
Das Problem ist bekannt. Es liegt an der API hier: https://api.corona-zahlen.org/docs/ Die erlaubt nur 15 Aufrufe pro Minute. Normalerweise kein Problem, aber in deinem Setting kommst du da an die Grenze. Über die API kommen aber nur
- Der Impfstatus
- Der Wert für DE
- Die Frozen-Werte

Wenn du also bei deinen Widgets teilweise den Impfstatus ausblenden kannst (`vac=n`) oder den Wert für Deutschland (`de=n`) oder die berechneten Werte statt der Frozen-Werte verwenden kannst (`frozen=n`) sollte das Problem verschwinden.

**Comment by Copperlanding** [comment]
Hab ein ähnliches Problem: „2021-06-07 10:32:58: Error on line 502:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states')“. Auch beim ändern der Werte wie oben vorgeschlagen funktioniert das Widgets leider nicht mehr. 
Hab Version Version: 1.8.0b. Kann es daran liegen?

**Comment by marcusraitner** [comment]
Du kannst natürlich mal die neuste Version installieren, aber daran sollte es nicht liegen. Warte einfach mal eine Minute und ruf das Widget nochmal auf; dann sollte es gehen.

**Comment by Copperlanding** [comment]
Hab die neue Version 19 eingesetzt und die produziert leider den gleichen Fehler:
„2021-06-07 10:41:59: Error on line 534:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states')“. 
Herzliche Grüße

**Comment by marcusraitner** [comment]
Ich vermute zusätzlich dass es im Moment ein Problem mit der API gibt. Aber mit `vac=n;de=n` geht es bei mir.

**Comment by Copperlanding** [comment]
Ja mit vac= n geht’s bei mir jetzt auch. Danke!

Marcus Raitner ***@***.***> schrieb am Mo. 7. Juni 2021 um
10:47:

**Comment by marcusraitner** [comment]
Die API liefert einen Fehler: `{"error":{"message":"An error occurred.","details":"Cannot read property 'state' of undefined","stack":"TypeError: Cannot read property 'state' of undefined\n    at Object.<anonymous> (/usr/src/app/src/data-requests/vaccination.ts:253:15)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/vaccination.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}`

**Comment by Copperlanding** [comment]
Kann ich was ändern?

Marcus Raitner ***@***.***> schrieb am Mo. 7. Juni 2021 um
10:58:

**Comment by marcusraitner** [comment]
Nein; nur die Parameter entsprechend setzen, damit die Calls der API vermieden werden.

**Comment by marcusraitner** [comment]
Hier mehr Infos dazu: https://github.com/marlon360/rki-covid-api/issues/233 

Kurz: Das RKI hat das Format des Excels geändert. Digitalisierung in D im Jahr 2021 🤦‍♂️

**Comment by Copperlanding** [comment]
Oh jeh. Deutschland’s RKI in der Steinzeit.
Hoffe Ihr großartiges Script funktioniert bald wieder.  Ich schau hier
jeden Tag mal rein oder besser abonniere Ihren Kanal.
Herzliche Grüße und Danke für die tolle Arbeit!
Frank Alexander von Keutz


Marcus Raitner ***@***.***> schrieb am Mo. 7. Juni 2021 um
11:51:

**Comment by marcusraitner** [comment]
Ja, es ist schon erbärmlich … aber bestimmt funktioniert es bald wieder.

**Comment by kissnofrog** [comment]
Where and how in the script do you enter this vac=n ?

**Comment by PeterSchimmel** [comment]
In scriptable:

- Tap the 3 dots on the script's tile, there should be a line

_var showVaccination = true;_

- change to 

_var showVaccination = false;_

- Hit "Done" in the upper left 

Done!

**Comment by marcusraitner** [comment]
Thanks for your support @PeterSchimmel!

**Comment by dennerforen** [comment]
> In scriptable:
> 
> * Tap the 3 dots on the script's tile, there should be a line
> 
> _var showVaccination = true;_
> 
> * change to
> 
> _var showVaccination = false;_
> 
> * Hit "Done" in the upper left
> 
> Done!

https://gist.github.com/marcusraitner/a1b633625d1016498eaaab712461dfc4#gistcomment-3772561

Better way, less errors

**Comment by marcusraitner** [comment]
You're right, @dennerforen. No need to change the code.

@kissnofrog Just do a long tap on the widget on your home screen; then it will flip and you will have at the bottom a field for the parameters. It is also described here: https://www.iphone-ticker.de/covid-19-dashboard-iphone-widget-zeigt-lokale-inzidenzen-174666/

**Comment by marcusraitner** [comment]
API has been adjusted to the changed Excel of the RKI; everything's up an running again.
