### ISSUE TITLE
Error on line 534:48

### ISSUE THREAD

**Issue by MrMcFly85** [marcusraitner/COVID-19-Dashboard#64]
Seit heute Fehlermeldung beim Ausführen über Scriptable (mit und ohne Parameter):

Exception Error on line 534:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states')

**Comment by marcusraitner** [comment]
Ist ein temporäres Problem der API; s. #62

**Comment by marcusraitner** [comment]
Mit `vac=n;de=n` geht es aber trotzdem.

**Comment by muescha** [comment]
Bei mir ist es in 535:48

**Comment by muescha** [comment]
Wäre es möglich nen Fallback zu implementieren, wenn dieser Fehler Auftritt? 

zB den Parameter automatisch anpassen. 

Oder bei einem Fehler nur den fehlerhaftem Wert nicht anzeigen, die restlichen verfügbaren Werte wie bisher anzeigen.

**Comment by marcusraitner** [comment]
Ja, das Fehlerhandling muss verbessert werden. Dazu gibt es schon einen Issue: #10

**Comment by marcusraitner** [comment]
Duplicate of #62
