### ISSUE TITLE
Fehler beim Starten des Scripts

### ISSUE THREAD

**Issue by gunti-2020** [marcusraitner/COVID-19-Dashboard#65]
![06E0619E-437E-4855-92AE-ACD81CE38C4E](https://user-images.githubusercontent.com/73196506/121135488-d86feb00-c834-11eb-99cc-13d9e678c133.jpeg)

Das Neuste Coding habe ich heruntergeladen und damit bekomme ich den Fehler

**Comment by marcusraitner** [comment]
Siehe #62. Ist ein Problem der API. Bitte mit `vac=n` temporär deaktivieren.

**Comment by gunti-2020** [comment]
Sorry, ich bin habe keine Ahnung von dem Coding.
An welche Stelle, muss ich was einfügen?

**Comment by DonCojote** [comment]
Hallo, bitte einmal posten an welcher Stelle man es ergänzen kann. Unter den Parameters hat es bei mir nichts bewirkt. 

LG
Alex

**Comment by marcusraitner** [comment]
Sollte bei den Parametern gemacht werden. Wie hier beschrieben https://www.iphone-ticker.de/covid-19-dashboard-iphone-widget-zeigt-lokale-inzidenzen-174666/?unapproved=1325101&moderation-hash=849dab764fe1e837c976d778a7860299#boo

**Comment by PeterSchimmel** [comment]
Habs kurz unter #62  geschrieben, sonst kommt das noch öfter 
https://github.com/marcusraitner/COVID-19-Dashboard/issues/62#issuecomment-856638567

**Comment by marcusraitner** [comment]
> Habs kurz unter #62 geschrieben, sonst kommt das noch öfter
> [#62 (comment)](https://github.com/marcusraitner/COVID-19-Dashboard/issues/62#issuecomment-856638567)

Danke! Ich muss das unbedingt dokumentieren unter #58
