### ISSUE TITLE
Frage zu Zahlen (R-Wert und aktuelles Delta)

### ISSUE THREAD

**Issue by emufan** [marcusraitner/COVID-19-Dashboard#66]
Tolles Widget. Wirklich fantastisch, insb. auch in die Inline-Kommentare, usw.

Dennoch zwei Fragen:

1. Warum wird das letzte Delta, d.h. das "letzte Plus" nicht angezeigt? Sondern nur die davor. 

2. Du nimmst bei R-Wert den 4-Tage Schätzer und nicht den sonst verwendeten 7-Tage Schätzer. Gibt es dafür einen Grund, außer, dass das der einzige in der https://api.corona-zahlen.org/germany ist? Vergleiche: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile

**Comment by marcusraitner** [comment]
> Tolles Widget. Wirklich fantastisch, insb. auch in die Inline-Kommentare, usw.
> 

Danke für die Anerkennung.

> Dennoch zwei Fragen:
> 
> 1. Warum wird das letzte Delta, d.h. das "letzte Plus" nicht angezeigt? Sondern nur die davor.

Darauf hatte ich schon gewartet und lange überlegt, wie ich es mache. Ich muss ein bisschen ausholen: Das RKI berechnet die Inzidenz für heute auch den sieben letzten Tagen (also bis einschließlich gestern). Rein logisch würde ich das nicht als Inzidenz für heute verkaufen, sondern als die für gestern (und in einer früheren Version meines Widgets war das auch so, hat aber die Leute verwirrt). Die Fallzahl für heute ist in dieser Inzidenz aber nicht enthalten und auch gar nicht verfügbar. Für heute steht der Zuwachs als erst morgen fest und wird dann auch angezeigt.  

> 2. Du nimmst bei R-Wert den 4-Tage Schätzer und nicht den sonst verwendeten 7-Tage Schätzer. Gibt es dafür einen Grund, außer, dass das der einzige in der https://api.corona-zahlen.org/germany ist? Vergleiche: https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen.xlsx?__blob=publicationFile

Ja, das ist der einzige Grund. Wenn du bei der API den Change-Request einstellst und es dort implementiert ist, dann kann ich das gerne übernehmen (oder wenn du eine andere API dafür hast)

**Comment by emufan** [comment]
Wow, danke für die schnelle Rückmeldung.

> Die Fallzahl für heute ist in dieser Inzidenz aber nicht enthalten und auch gar nicht verfügbar. Für heute steht der Zuwachs als erst morgen fest und wird dann auch angezeigt.

Hm, aber die von gestern sind aber doch verfügbar.  Im Beispiel +2 für den Heidekreis. Wie auf dem RKI-Dashboard, usw. Angezeigt werden aber nur die Werte von vorgestern, vorvorgestern, usw. was hier +0, +0, +0, +7 usw. ist.

Hier, wo sie mMn - sicher u. a - auch in der API sind.

```
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall%20IN(1,-1)+AND+IdLandkreis=03358&objectIds=&time=&resultType=standard&outFields=AnzahlFall&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&outStatistics=%5B%7B%22statisticType%22:%22sum%22,%22onStatisticField%22:%22AnzahlFall%22,%22outStatisticFieldName%22:%22value%22%7D%5D%0D%0A&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token=
```

> 7-Tage Schätzer: oder wenn du eine andere API dafür hast

Habe gesehen (gesucht, als ich nachvollziehen wollte, warum Deine Zahl abweicht) dass sich andere dies so ziehen aus
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile

```
const apiRUrl = `https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Projekte_RKI/Nowcasting_Zahlen_csv.csv?__blob=publicationFile`
const CONFIG_CSV_RVALUE_FIELD = 'Schätzer_7_Tage_R_Wert' // numbered field (column), because of possible encoding changes in columns names on each update

---

async function getRValue() {
    const rDataStr = await new Request(apiRUrl).loadString()
    const rData = parseRCSV(rDataStr)
    let lastR = 0
    rData.forEach(item => {
        if (typeof item[CONFIG_CSV_RVALUE_FIELD] !== 'undefined' && parseFloat(item[CONFIG_CSV_RVALUE_FIELD].replace(',','.')) > 0) {
            lastR = item;
        }
    })
    return (lastR) ? parseFloat(lastR[CONFIG_CSV_RVALUE_FIELD].replace(',','.')) : lastR
}
```

**Comment by marcusraitner** [comment]
Cool. Danke für den Code-Schnipsel. Das kann ich auf jeden Fall so machen und mir den API-Aufruf sparen.

Was die Fallzahlen betrifft, das ist komisch, denn mein Aufruf ist der folgende
```
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_RKI_Sums/FeatureServer/0/query?where=idLandkreis%3D+03358+AND+Meldedatum+%3E+%2704-29-2021%27&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=Meldedatum&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=json&token=
```

Und der liefert für gestern den Wert 0 und darum steht auch +0 in der Grafik:

![IMG_1190](https://user-images.githubusercontent.com/65543240/121190565-7aaac580-c86b-11eb-8a19-f9d73bc94c31.jpeg)

Ich bin mir echt unschlüssig, warum das beim RKI nicht zusammenpasst …

**Comment by emufan** [comment]
> Ich bin mir echt unschlüssig, warum das beim RKI nicht zusammenpasst …

Ich bin nun dahintergekommen. Wenn das RKI im eigenen Dashboard zeigt:
![image](https://user-images.githubusercontent.com/22775515/121205966-5ef9ec00-c878-11eb-8d1d-674b9fa9edf8.png)
z.b. hier für den LK Unstrut-Hainich-Kreis 16064, so sind das die gestern gemeldeten Neuinfektionen, da alle von gestern sind und keine nachgemeldet wurden.

In diesem Beispiel stimmt dann die 12 aus Deinem [Aufruf](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_RKI_Sums/FeatureServer/0/query?where=idLandkreis=16064+AND+Meldedatum%3E+'06-05-2021'&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) mit dem errechneten aus der anderen API zusammen. Rechne [hier](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall+IN(1,-1)+AND+idLandkreis=16064&objectIds=&time=&resultType=standard&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) die Summe aus den 6 AnzahlFall-Zahlen.

Nehme ich den obigen Heidekreis, so wirft die von Dir genutzt API ja 0, siehe [hier](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/Covid19_RKI_Sums/FeatureServer/0/query?where=idLandkreis=03358+AND+Meldedatum%3E+'06-05-2021'&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) wogegen das RKI-Dashboard und die andere API [hier](https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/RKI_COVID19/FeatureServer/0/query?where=NeuerFall+IN(1,-1)+AND+idLandkreis=03358&objectIds=&time=&resultType=standard&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=html&token=) 2 zeigt:
![image](https://user-images.githubusercontent.com/22775515/121207359-81403980-c879-11eb-8573-8ca4d1c02850.png)
Nur sind das die Summe der insgesamt gestern gemeldeten und nachgemeldeten Fälle, Und das zeigen die anderen Dashboards auch an, sind aber ja tatsächlich nicht die Fälle von gestern, sondern haben nur die Relevanz für die Gesamtzahlen.

Damit hätte Donau-Ries z.B. auch "gestern" +6, aber siehe hier:
![image](https://user-images.githubusercontent.com/22775515/121208956-bef19200-c87a-11eb-8de2-cb62a22d7699.png)

Mein aktuelles Fazit: Dein Dashboard und die von Dir genutzt API zeigt es (auch subjektiv für mich) richtiger an, da es nur die Fälle von gestern und nicht die nachgemeldeten Fälle anzeigt, die ja eh nicht in die eingefrorene Statistik eingehen.

**Comment by marcusraitner** [comment]
> Mein aktuelles Fazit: Dein Dashboard und die von Dir genutzt API zeigt es (auch subjektiv für mich) richtiger an, da es nur die Fälle von gestern und nicht die nachgemeldeten Fälle anzeigt, die ja eh nicht in die eingefrorene Statistik eingehen.

Ok, allerdings habe ich mit der API die ich nutze schon den Effekt, dass sich die Werte nachträglich ändern, d.h. wenn ich morgen einen Abruf mache, dann können die Zahlen je Meldedatum andere sein als heute. Ich war bisher immer der Meinung, dass das an den Nachmeldungen läge. Darum gibt es ja den Parameter `frozen=y` wo ich dann via https://api.corona-zahlen.org/ die offizielle Inzidenz des Tages aus dem Excel des RKI hole (da hole ich aber keine Fallzahlen)

**Comment by emufan** [comment]
Ja ich weiß. Wusste bis heute und durch die Vergleiche aber tatsächlich nicht, dass die RKI-Zahlen, die überall veröffentlicht und verwendet werden, auch die Nachmeldungen beinhalten. War die Recherche der Zahlen immerhin diese Erkenntnis wert. ;-)

**Comment by marcusraitner** [comment]
Wieder was gelernt. Ich meine aber, dass für die Maßnahmen aber nur die eingefrorenen Werte gelten, oder?

**Comment by emufan** [comment]
Denke auch. mMn werden die Nachmeldungen in die letzte/aktuelle Inzidenz reingerechnet, wenn in den letzten 7 Tagen erkrankt/nachgemeldet, aber nicht in die letzten Inzidenzen reingerechnet, d.h. die bleiben eingefroren. Das machst Du ja zum Glück (optional, per default) anders, was ich auch ehrlicher/repräsentativer finde.

**Comment by marcusraitner** [comment]
Ja. Ursprünglich hatte ich die "eingefrorenen" Werte auch gar nicht im Angebot, weil es mir falsch / unlogisch erschien. Ich will ja wissen, wie die Lage wirklich ist. Aber natürlich macht es für die Maßnahmen auch Sinn, diese Zahlen anzuzeigen. Das eigentliche Problem ist ja aber doch, dass wir in eineinhalb Jahre Pandemie immer noch diese Nachmeldungen haben und immer noch nicht einen reibungslosen Fluss dieser doch scheinbar so wichtigen Zahlen habe. Es ist schon der Wahnsinn, wie amateurhaft hier die Daten fließen …

**Comment by marcusraitner** [comment]
Im Rahmen von #75 haben ich jetzt auch den 7-Tages Schätzer (aufgrund einer Änderung der API) eingebaut; daher würde ich das hier jetzt mal schließen.
