### ISSUE TITLE
COVID-19 Dashboard

### ISSUE THREAD

**Issue by Rogman22** [marcusraitner/COVID-19-Dashboard#67]

**Comment by marcusraitner** [comment]
Worum geht's?

**Comment by Rogman22** [comment]
Hi, ich wollte Ihr Widget installieren, komme aber mit dem System nicht zurecht. Sorry, aber Sie müssen sich nicht die Mühe machen es mir zu erklären.

**Comment by marcusraitner** [comment]
Vielleicht hilft der Artikel hier https://www.iphone-ticker.de/covid-19-dashboard-iphone-widget-zeigt-lokale-inzidenzen-174666/
