### ISSUE TITLE
TypeError undefined is not an object 

### ISSUE THREAD

**Issue by ABrolund** [marcusraitner/COVID-19-Dashboard#68]
this error disappear if you use vac=n - Parameter 
It seems https://api.corona-zahlen.org/vaccinations is not valid anymore ,
It returns: 

{"error":{"message":"An error occurred.","details":"Cannot read property 'state' of undefined","stack":"TypeError: Cannot read property 'state' of undefined\n    at Object.<anonymous> (/usr/src/app/src/data-requests/vaccination.ts:253:15)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/vaccination.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}

Please have a look

**Comment by marcusraitner** [comment]
Indeed! Is already discussed in #62 and also addressed at the API https://github.com/marlon360/rki-covid-api/issues/233 

Long story short: RKI changed the format of their respective excel 🤦‍♂️
