### ISSUE TITLE
Zahlen stehen „ineinander“

### ISSUE THREAD

**Issue by RosoV89** [marcusraitner/COVID-19-Dashboard#69]
Wie kann man das Problem lösen, dass die Zahlen nicht mehr ineinander stehen?

**Comment by RosoV89** [comment]
![Uploading 8424AD0C-4D57-4A6A-9528-5F79AEEB62F7.jpeg…]()

**Comment by marcusraitner** [comment]
Irgendwie lädt dein Screenshot noch hoch. Wo genau ist das Problem?

**Comment by RosoV89** [comment]
![Uploading 827DB804-0621-4434-8EB0-C7B9A707559C.jpeg…]()

**Comment by RosoV89** [comment]
![6E9CCAA6-8756-4300-84F7-B330EE3F2543](https://user-images.githubusercontent.com/73339863/121194621-328da200-c86f-11eb-9d7c-ed187dd73a07.png)

**Comment by RosoV89** [comment]
Jetzt hat es geklappt

**Comment by marcusraitner** [comment]
Danke! Wer rechnet denn auch mit solchen Extremfällen 😉 Da kannst du wenig machen, außer dir täglichen Fallzahlen ausblenden (`daily=n`). Ich lass das mal offen und überlege, ob und wie ich das verbessern könnte.

**Comment by RosoV89** [comment]
Naja, insgeheim hatte ich schon gehofft, dass wir solche "Extremfälle" im Sommer bekommen 😂

**Comment by marcusraitner** [comment]
Ja, ja, ich auch. Extrem ist auch eher der schnelle Abfall; denn wären da nicht die hohen Balken, hätten wir auch kein Problem.

**Comment by emufan** [comment]
Ist bei uns nun auch so. Liegt aber mE nur wenig an dem extremen Abfall sondern wäre auch so, wenn alle Tage 0 wären oder wenn Inzidenzen vom LK geringer als BL oder DE, usw. Letzteres ist hier der Fall.

Könntest Du nicht die Inzidenz so setzen (y-Position berechnen), da wirklich schön so, direkt über dem Balken in den Standardfällen, wie jetzt, aber immer prüfen ob y-Achse Inzidenz mind. x Pixel über der jeweiligen Delta-Zahl ist und dies in den Fällen als Minimum korrigieren/setzen?

**Comment by marcusraitner** [comment]
@emufan du meinst also, einfach den Inzidenzwert soweit nach oben schieben, dass nichts mehr überlappt? Das ginge schon …

**Comment by emufan** [comment]
Wäre meine spontante Idee/Lösung gewesen. Berechnen wie vorher. Dann kurz prüfen ob mind x Pixel über dem anderen Wert, ansonsten diese x Pixel über dem anderen Wert. Sonst bleibt alles wie es ist, da wirklich perfekt.

**Comment by marcusraitner** [comment]
Wäre einen Versuch wert. Danke dir.

**Comment by marcusraitner** [comment]
@emufan Hast du zufällig einen Landkreis, wo ich das gut testen kann heute Abend?

**Comment by RosoV89** [comment]
Probier mal Landkreis Vorpommern-Rügen
Siehe meinen Screenshot am Anfang des Threads :)

**Comment by janhuddel** [comment]
Im Landkreis Plön zum Beispiel:
![IMG_8299](https://user-images.githubusercontent.com/3514263/121809608-bf64a100-cc5d-11eb-8206-f046656bd96b.jpeg)

**Comment by marcusraitner** [comment]
Danke euch allen. Jetzt habe ich genügend Test-Cases

**Comment by marcusraitner** [comment]
So richtig gefällt mir die Lösung nicht … 

![IMG_1220](https://user-images.githubusercontent.com/65543240/121819415-45e4a700-cc8d-11eb-965f-bb6b9e148eef.jpeg)

**Comment by emufan** [comment]
Hm, mir eigentlich schon. Sehr sogar. Besser als alles oben in einer Reihe zu haben oder so. Aber klar. Geschmackssache. 

Ist das hier irgendwo in einem File? Dann würde ich mir das gerne sichern und verwenden.

**Comment by marcusraitner** [comment]
@emufan Hast Recht: ist besser wie vorher und ja eher ein Sonderfall. Ich habe es jetzt gemerged. Schaus es dir mal an.
