### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by emufan** [marcusraitner/COVID-19-Dashboard#73]
Seit ein paar Tagen funktioniert dieses Widget (und aber auch andere) nicht? 

Ist eine oder sind mehrere APIs down? Dachte, kurzer Schluckauf, o.Ä., aber bleibt dauerhaft. Hatte aber noch keinen gemeldeten Fehler gesehen.

**Comment by marcusraitner** [comment]
Was genau funktioniert denn nicht? Und mit welchen Parametern? Bei mir hier sieht alles gut aus …

**Comment by Drail0r** [comment]
Ich kann den Fehler nachvollziehen, bei mir liegt es am de-Parameter. Mit y lädt das Widget gar nicht, mit n ohne Probleme.

**Comment by marcusraitner** [comment]
Hmm, bei mir geht es auch bei `de=y`. Was habt ihr sonst für Parameter und welcher Fehler kommt?

**Comment by SdI7IHd** [comment]
Hallo zusammen,
Selbes Problem bei mir: mit de=y ging es teilweise, Fehler kam aber zurück.
Die Meldung bei mir ist:
Error on line 587:48: TypeError: undefined is not an object (evaluating 'vaccData.data.states')

PS: meine Parameter sind loc= 52.3946900, 9.8345100; de=n; rki=y;frozen=n;daily=y;vac=y

**Comment by toddy1986** [comment]
Bei mir mit:
50.13,8.91;frozen=y;vac=y;rki=y;de=n;decimal=y;theme=rki;days=5
Keine Probleme. Sobald ich de=y setze habe ich selbiges Problem.

**Comment by dploeger** [comment]
Bei mir ist es

loc= 51.66055211802168,7.835920751102115;de=y;beds=n

Funktioniert nur mit de=n ungefähr seit gestern Mittag.

**Comment by marcusraitner** [comment]
Ok, verstehe. Ihr habt das Widget vermutlich alle mehrfach für verschiedene Orte auf dem Homescreen. Der Fehler kommt wenn http://api.corona-zahlen.org mehr als 15 Mal pro Minute aufgerufen wird. Aus der API kommen die Impfzahlen, der Wert für DE und die Frozen-Werte. Ihr könnt also Aufrufe sparen, wenn ihr bei ein paar der Widgets `vacc=n` oder `de=n` oder auch `frozen=n` setzt. Oder natürlich weniger Widgets …

**Comment by emufan** [comment]
Nee, https://api.corona-zahlen.org/germany ist down, oder?

**Comment by marcusraitner** [comment]
Oh nein, dann hat das RKI mal wieder am Excel rumgespielt und das ist in der API noch nicht nachgezogen. Das hatten wir schon mal. Scheint den R-Wert zu betreffen. Also `de=n` sollte ein workaround sein.

**Comment by marcusraitner** [comment]
Siehe https://github.com/marlon360/rki-covid-api/issues/245

**Comment by dploeger** [comment]
Aber mit den mehreren Widgets hast Du bei mir Recht, @marcusraitner. Ich habe eins für den Heimat- und eins für den Urlaubsort.

**Comment by marcusraitner** [comment]
> Aber mit den mehreren Widgets hast Du bei mir Recht, @marcusraitner. Ich habe eins für den Heimat- und eins für den Urlaubsort. 

Das sollte aber kein Problem sein, weil das sicher weniger als 15 Aufrufe sind.

**Comment by Toni-99** [comment]
Ich denke, dass es hier nur um den /germany Endpunkt handelt. Das RKI soll die Excel Tabelle zum herausgeben der R-Werte anscheinend zu einer CSV Datei umggemünzt haben. Daher der Fehler, dass die Tabelle nicht konvertiert werden kann... Es wäre eine sehr feine Sache, wenn sich ein TypeScript Entwickler dem annehmen könnte, damit dieser absolut nervige (und unnötige) Bug (Vielen Dank an dieser Stelle ans RKI) behoben wird c:

**Comment by marcusraitner** [comment]
> Ich denke, dass es hier nur um den /germany Endpunkt handelt. Das RKI soll die Excel Tabelle zum herausgeben der R-Werte anscheinend zu einer CSV Datei umggemünzt haben. Daher der Fehler, dass die Tabelle nicht konvertiert werden kann... Es wäre eine sehr feine Sache, wenn sich ein TypeScript Entwickler dem annehmen könnte, damit dieser absolut nervige (und unnötige) Bug (Vielen Dank an dieser Stelle ans RKI) behoben wird c:

Normalerweise beheben die Kollegen recht schnell https://github.com/marlon360/rki-covid-api/issues/245 

Der eigentliche Skandal ist aber doch, wie das RKI hier Daten bereitstellt (und vermutlich ist die Datensammlung nicht viel besser … Fax sag ich nur).

**Comment by marlon360** [comment]
https://api.corona-zahlen.org/germany läuft wieder!

**Comment by marcusraitner** [comment]
> https://api.corona-zahlen.org/germany läuft wieder!

Danke für's Bescheid geben, @marlon360!

**Comment by dploeger** [comment]
Kann ich bestätigen. de=y geht wieder. 👍
