### ISSUE TITLE
R-Wert ist NaN

### ISSUE THREAD

**Issue by pike55** [marcusraitner/COVID-19-Dashboard#75]
Hallo,

zunächst mal vielen Dank für das super Widget. Ich finde es extrem hilfreich! 

Seit ein paar Tagen wird bei der R-Wert aber nur noch als NaN angezeigt. Ich habe mit meinen (begrenzten) Fähigkeiten mal geguckt, woran das liegen könnte. Offenbar hat sich die JSON-Antwort von https://api.corona-zahlen.org/germany geändert. Der R-Wert kommt da nun als rValue4Days und rValue7Days zurück.

Habe daraufhin die Code-Zeile 801 bei mir lokal geändert:

`}).format(germanyData.r.rValue7Days.value), rRect, dayColor, Font.mediumSystemFont(20));`

So klappt es bei mir wieder mit dem R-Wert.

Danke & Gruß

**Comment by marcusraitner** [comment]
Danke Dir! Ist mir heute auch aufgefallen. Danke für den Fix. Werde das anpassen und auch den 7-Tages-Wert nehmen.

**Comment by marcusraitner** [comment]
Ist jetzt behoben.
