### ISSUE TITLE
Problem mit frozen=y

### ISSUE THREAD

**Issue by toddy1986** [marcusraitner/COVID-19-Dashboard#77]
Folgende Parameter nutze ich:

50.13,8.91;frozen=n;vac=y;rki=y;de=y;decimal=y;theme=rki;rval=y;days=5

Setze ich frozen auf y wird mir „keine Statistik gefunden“ angezeigt. Wurde an der API rumgebastelt?

**Comment by marcusraitner** [comment]
Danke. Ja, da hat vermutlich das RKI wieder am Excel gespielt 🙄 ich habe das in der API adressiert: https://github.com/marlon360/rki-covid-api/issues/265

**Comment by marcusraitner** [comment]
War dort schon bekannt; s. https://github.com/marlon360/rki-covid-api/issues/264

**Comment by toddy1986** [comment]
Geht wieder

**Comment by marcusraitner** [comment]
Stimmt! Danke.
