### ISSUE TITLE
Anzahl Zweit geimpfte

### ISSUE THREAD

**Issue by Fran71** [marcusraitner/COVID-19-Dashboard#79]
Hallo,

wie bekomme ich die Zahl der Zweit geimpften in den Balken?
In Bayern kommen die Zahlen 61% und 57% langsam ineinander.

Vielen Dank!
Gruß Frank

**Comment by marcusraitner** [comment]
Hallo Frank, ist mir auch aufgefallen. Korrigiere ich abends. Bei mir ist das die folgende Zeile 622:

`vaccinationTextRect = new Rect(10, (1 - quoteBooster / 100) * vaccinationBottom - 26, vaccinationWidth, 22);`

Wenn du das -26 wegnimmst, passt es.

**Comment by marcusraitner** [comment]
Ist behoben im master
