### ISSUE TITLE
Error on line 389:48

### ISSUE THREAD

**Issue by toddy1986** [marcusraitner/COVID-19-Dashboard#8]
Hi Marcus,

vielen Dank für dein tolles Widget und die ständigen Neuerungen. Würde dir echt gerne was bei Paypal zukommen lassen…

Erhalte leider mit V1.5 manchmal folgende Meldung (manchmal lädt das Widget auch ganz normal):

![BFE21191-30F0-42AE-B388-1F7BF3F1AE10](https://user-images.githubusercontent.com/83943893/118404207-2f3d3700-b672-11eb-98b6-b9814f4b7a12.png)

**Comment by marcusraitner** [comment]
Hi, danke für dein Feedback. Vielleicht richte ich ja hier irgendwann mal einen Spendenbutton ein; oder einfach via [Steady](https://steadyhq.com/de/fuehrungerfahren/about), das ich mal für mein Blog eingerichtet habe.

Zu deinem Fehler. Das liegt vermutlich an der corona-api von der ich diese Impfdaten hole. Die erlaubt nur 15 Anfragen pro Minute. Jeder Aufruf meines Widgets produziert zwei und wenn du noch andere Widgets hast, die auch darauf zugreifen oder einfach schnell hintereinander aufrufst, dann passiert das schon mal. Du könntest auch im Code den Debug-Schalter mal auf true setzen, dann siehst du im Fehlerfall die Antwort von der API.

**Comment by toddy1986** [comment]
Danke:

{"error":"Too Many Requests","message":"You are only allowed to make 15 requests every minute. Retry in 49.035 seconds. This is a free service and you should not abuse it. If you need more requests, you can host the server yourself (https://api.corona-zahlen.org/docs/#host-it-yourself).","code":429}

**Comment by marcusraitner** [comment]
Ja, das hatte ich vermutet. Wann passiert das bei Dir? Du wirst ja nicht mein Skript x-mal pro Minute aufrufen … evtl. könnte ich auch noch einen Aufruf sparen für den Fall `de=n` … muss mal schauen, ob ich da sauber war.
