### ISSUE TITLE
Fehler in Zeile 588

### ISSUE THREAD

**Issue by ibaga2k** [marcusraitner/COVID-19-Dashboard#80]
Hallo,
ein Fehler in Zeile 588:48 wird gemeldet. Dort wird der Impffortschritt ausgewertet. 
„TypeError: undefined is not an object (evaluating ’vacData.data.states’“
Gruß Karsten

**Comment by marcusraitner** [comment]
Vermutlich hast du zu oft hintereinander das Widget aufgerufen und / oder mehrere Widgets mit verschiedenen Orten laufen. Die API dahinter (für die Impfung, die Frozen-Werte und den Wert für DE) verträgt nur 15 Aufrufe pro Minute. Probier es bitte nach einer gewissen Zeit nochmal.

**Comment by Copperlanding** [comment]
Leider nein, ich habe den gleichen Fehler in Zeile 588:48 beim ersten Aufruf des Widgets. 
Herzliche Grüße

**Comment by marcusraitner** [comment]
Komisch, weil die Schnittstelle für die Impfungen eigentlich funktioniert; was Probleme macht, ist die Schnittstelle für den Wert für Deutschland bzw. die für die einzelnen Landkreise; vgl. https://github.com/marlon360/rki-covid-api/issues/276

Mit welchen Parametern ruft ihr das Widget auf?

**Comment by ibaga2k** [comment]
Ich habe folgende Parameter eingegeben:
„49.384,11.212;de=y;theme=rki“
mit dem Parameter „de=y“ bekomme ich die Fehlermeldung, ohne diesen Parameter funktioniert es bei mir

**Comment by Copperlanding** [comment]
const debug = true
;

// Set to true for an image background, false for no image.
const imageBackground = false;

// Set to true to reset the widget's background image.
const forceImageUpdate = false;

// Show also the incidence for Germany in total
var showGermanyValue = true;

// Show also the R-Value (only if showGermanyValue == true)
var showRValue = true;

// Toggle showing of vaccination status
var showVaccination = true;

// Toggle showing of ICU beds
var showIcu = true;

// show daily portion of incidence
var showDaily = true;

// Show frozen value for incidence instead of calculating it.
var useFrozen = false;

// number of days to show in detail
var detail = 5;

// show values for the state
var showBl = true;

Bei mir das Gleiche: Läuft mit dem Parameter „de=False“
Herzliche Grüße


ibaga2k ***@***.***> schrieb am Fr. 3. Sept. 2021 um 09:43:

**Comment by marcusraitner** [comment]
Danke euch. Wenn ihr `de=n` bzw. `showGermanyValue = true` setzt, sollte es aktuell funktionieren bis die API wieder funktioniert.

**Comment by Copperlanding** [comment]
Danke, klappt!

Marcus Raitner ***@***.***> schrieb am Fr. 3. Sept. 2021 um
10:00:

**Comment by ibaga2k** [comment]
Bei mir funktioniert nur „de=n“ oder „showGermanyValue = false“, mit „True“ stürzt die Anwendung ab. Aber mit diesem Workaround läuft es. 
Vielen Dank für die schnelle Hilfe 👍

**Comment by marcusraitner** [comment]
Ja, stimmt. Mein Fehler oben. Ich meinte natürlich `=false`

**Comment by Donigi-77** [comment]
Sobald ich dies showGermanyValue = true  ändere kommt der Fehler 188:279
![image](https://user-images.githubusercontent.com/89263293/132090983-96c17cdd-073d-40b9-a2ab-71e99eec0338.jpeg)
Hat sonst jemand noch diesen Fehler?

**Comment by marcusraitner** [comment]
@Donigi-77 hast du die Koordinaten als Parameter mitgegeben oder werden die vom iPhone ermittelt?

**Comment by Donigi-77** [comment]
@marcusraitner wird vom iPhone ermittelt

**Comment by marcusraitner** [comment]
Ok, dann geht da was schief. Du könntest ja mal in Zeile 416 (also nach dem if else in dem die Location ermittelt wird) diese Ausgabe einbauen `console.log(location);` und dann das Script gleich im Editor mit dem Play-Symbol dort laufen lassen. Dann solltest du in der Ausgabe (das zweite Icon von links) sehen, was da an Location zurück kommt von deinem iPhone.

**Comment by Donigi-77** [comment]
Danke ich werde es versuchen. Nur zur Info wenn ich das Script in der Console ausführe funktioniert es aber nicht wenn ich es über die App mache. Ich gebe Feedback ob das die Lösung ist. Danke nochmals für den schnellen Lösungsvorschlag.

**Comment by marcusraitner** [comment]
Das ist aber komisch. Was heißt für dich "über die App"? In Scriptable einfach auf das Skript tippen? Mein Vorschlag wird das Problem nicht lösen, ich wollte nur sehen, was in der Location Variable steht … aber wenn es da im Editor funktioniert, wird uns das nicht helfen.

**Comment by Donigi-77** [comment]
Entschuldige meine unverständliche Aussage: also wenn ich das Script in der Console ausführe kommt dieses Bild ![image](https://user-images.githubusercontent.com/89263293/132092457-d9e15288-f601-4f75-9a86-2fd29ec401e2.png)
Und wenn ich dann auf close gehe kommt dies ![image](https://user-images.githubusercontent.com/89263293/132092486-adf6b034-ba31-4133-ac8d-919232fc778d.png). Ich hoffe das erklärt meine Aussage 😀

**Comment by Donigi-77** [comment]
@marcusraitner So habe deine Änderung eingefügt und meine Parameter in Scriptable gelöscht. Es funktioniert wieder 😄  Danke nochmals

**Comment by marcusraitner** [comment]
Ja, jetzt verstehe ich das besser. Wie hast du das Skript ausgeführt am Anfang. Warst du da im Editor und dann den Play-Button?

**Comment by marcusraitner** [comment]
> @marcusraitner So habe deine Änderung eingefügt und meine Parameter in Scriptable gelöscht. Es funktioniert wieder 😄  Danke nochmals

Sehr gut. Vermutlich hast du irgendwo bei den Parametern irgendeinen Fehler gehabt. Am besten du holst dir den Code einfach nochmal; dann wird rauch die Beschriftung der Impfungen besser dargestellt.

**Comment by Donigi-77** [comment]
> > @marcusraitner So habe deine Änderung eingefügt und meine Parameter in Scriptable gelöscht. Es funktioniert wieder 😄  Danke nochmals
> 
> Sehr gut. Vermutlich hast du irgendwo bei den Parametern irgendeinen Fehler gehabt. Am besten du holst dir den Code einfach nochmal; dann wird rauch die Beschriftung der Impfungen besser dargestellt.

In den Parametern habe ich deine Vorschläge rein wie z.B. rval =y;daily=y; usw. und dein de=n; als des als erstes nicht funktioniert hat. Alles gelöscht und es funktioniert wieder. 👍🏼

**Comment by marcusraitner** [comment]
Funktioniert wieder.
