### ISSUE TITLE
Impfquote überlagert sich 

### ISSUE THREAD

**Issue by preacha** [marcusraitner/COVID-19-Dashboard#82]
Hi,

danke für das tolle Script. Nutze es schon eine Weile aber seit einiger Zeit fällt mir auf, dass die Prozentwerte der Impfungen im Bundesland überlagern und so nicht mehr lesbar sind (iPhone X). Kannst du das fixen?
![E0246E61-18C5-4EFB-BD6C-A77F344C8F3D](https://user-images.githubusercontent.com/7067861/132344235-807ed182-c5d5-4c52-ae69-5d499fbcb544.jpeg)

**Comment by marcusraitner** [comment]
Danke! Ist schon behoben (#79), aber der Code ist nur hier bisher veröffentlicht und nicht drüben im gist. Wenn du dir den aktuellen Code hier holst, passt es wieder.
