### ISSUE TITLE
Hospitalisierungsrate

### ISSUE THREAD

**Issue by InkognitoXY** [marcusraitner/COVID-19-Dashboard#83]
Guten Morgen, 

da der Inzidenz nicht mehr den alleinigen Stellenwert besitzt um das Infektionsgeschehen zu monitorisieren, wollte ich mal fragen, ob Sie vielleicht noch die Hospitalisierungsrate vom RKI-Dashboard implementieren könnten. Wäre ein informativer Mehrgewinn. Vielen Dank & ein schönes Woe.

**Comment by marcusraitner** [comment]
Danke, das steht auf meiner To-Do-Liste. Allerdings gibt es Stand heute dafür keine API aus der ich die Daten beziehen könnten (die Digitalisierung unserer Behörden ist skandalös). Ich bleibe aber dran.

**Comment by marcusraitner** [comment]
Habe das bereits bei api.corona-zahlen.org eingesteuert: https://github.com/marlon360/rki-covid-api/issues/275

**Comment by Donigi-77** [comment]
Guten Abend @marcusraitner , ich wollte mal nachfragen wie es mit der Hospitalisierungsrate voran geht. Soweit ich das mitbekommen habe wurde das bei @marlon360 hinzugefügt. 
Vielen Dank und eine gute Nacht
Donigi-77

**Comment by marcusraitner** [comment]
Stimmt! Jetzt brauche ich nur noch eine gute Idee, wie und wo ich die darstelle. Vielleicht einfach unter dem Balken für das Bundesland?

**Comment by Donigi-77** [comment]
Man könnte aber auch die Intensivbetten in Hospitalisierung ändern? Nur so ein Gedanke. Grüße Donigi-77

**Comment by ghost** [comment]
Die Intensivbetten sind für den Landkreis, die Hospitalisierungsinzidenz für das Bundesland. Damit würde man die lokale Lage wesentlich ungenauer einschätzen können.

Leider gibt es noch keine API für die Hospitalisierungsinzidenz des Landkreis.

**Comment by marcusraitner** [comment]
> Die Intensivbetten sind für den Landkreis, die Hospitalisierungsinzidenz für das Bundesland. Damit würde man die lokale Lage wesentlich ungenauer einschätzen können.

Ich denke auch, dass wir beides anzeigen sollten. Vielleicht probiere ich es wirklich erst mal unterhalb des Balkens für die Inzidenz des Bundeslandes.

Gibt es eigentlich für die Hospitalisierungsinzidenz bundeseinheitliche Schwellwerte?

**Comment by ghost** [comment]
Also Bremen und Niedersachsen nehmen ganz andere Hospitalisierungsinzidenzen, als die die vom RKI für die Bundesländer bereitgestellt werden. Allgemein soll jeder Landkreis seine eigenen Grenzwerte an die lokalen Kapazitäten anpassen.

https://github.com/marlon360/rki-covid-api/issues/275#issuecomment-944159217

**Comment by marcusraitner** [comment]
Wie wäre es mit dieser Lösung? Im Moment kann ich leider nur immer den aktuellen Wert der Hospitalisierungen und der Inzidenz daraus anzeigen (die Verlaufsdaten habe ich nicht), aber besser also ganz ohne.

![IMG_0068](https://user-images.githubusercontent.com/65543240/139531307-4ab8a788-9d32-46a1-81c6-0b40aab0d787.jpeg)

**Comment by InkognitoXY** [comment]
Hallo Her Raitner,

das ist doch gut so. Ist auch ganz übersichtlich. Danke sehr!

Viele Grüße
Am 30. Okt. 2021, 13:34 +0200 schrieb Marcus Raitner ***@***.***>:

**Comment by ghost** [comment]
Es würde stimmiger aussehen, wenn ebenfalls weiße Schrift verwendet wird.

**Comment by marcusraitner** [comment]
> Hallo Her Raitner, das ist doch gut so. Ist auch ganz übersichtlich. Danke sehr! 

Danke. Dann werde ich das abends hoffentlich fertigstellen können.

**Comment by marcusraitner** [comment]
> Es würde stimmiger aussehen, wenn ebenfalls weiße Schrift verwendet wird.

Guter Punkt. Dann muss ich mir nur noch eine andere Hintergrundfarbe suchen.

**Comment by marcusraitner** [comment]
Probieren wir es mal so …

**Comment by ghost** [comment]
Das mit der Hospitalisierungsrate scheint aber noch Buggy zu sein. Bei mir wird 2.86 angezeigt obwohl wir bei über 6 sind. 
Jemand ne idee?

**Comment by marcusraitner** [comment]
Wo bist du denn? Kannst du einen Screenshot posten und eine Referenz, wie du auf die Abweichung kommst (Quelle)

**Comment by ghost** [comment]
> Das mit der Hospitalisierungsrate scheint aber noch Buggy zu sein. Bei mir wird 2.86 angezeigt obwohl wir bei über 6 sind.
> Jemand ne idee?

Vermutlich vergleichst du die Hospitalisierungsinzidenz vom [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) mit der vom [IVENA eHealth System](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html). 

[Weser Kurier](https://www.weser-kurier.de/deutschland-welt/hospitalisierungsindex-so-unterschiedlich-sind-die-zaehlweisen-doc7ijeoq17mfp1mfb4ii1b):
> Anders als das RKI und einige andere Bundesländer bemisst Niedersachsen die Krankenhausinzidenz aufgrund der täglichen Meldungen über das Ivena-System nach der Zahl aller Neuaufnahmen von Covid-Patienten binnen der letzten sieben Tage. „Dabei spielt es keine Rolle, wann sich diese Patienten mit dem Virus infiziert haben“, erklärt eine Sprecherin von Gesundheitsministerin Daniela Behrens (SPD). Folge: Die RKI-Quoten für Niedersachsen sind durchweg niedriger als die Werte des Landes selbst.

In Niedersachsen wird auch nicht berücksichtigt wo die Patienten herkommen. Also wenn Niedersachsen 50 Leute aufnimmt aus anderen Bundesländern, dann steigt der Wert vom [IVENA eHealth System](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html). Das lokale schwere Infektionsgeschehen wird damit dann allerdings nicht korrekt abgebildet.

Die Zählweise vom RKI ist auch nicht aussagekräftig, weil dort zählt jedes Intensivbett das positiv getestet ist, auch wenn die Person sich ein Bein gebrochen hat. [[RKI](https://www.rki.de/SharedDocs/FAQ/NCOV2019/gesamt.html)]

[Weser Kurier](https://www.weser-kurier.de/deutschland-welt/hospitalisierungsindex-so-unterschiedlich-sind-die-zaehlweisen-doc7ijeoq17mfp1mfb4ii1b):

> Für die Berechnung des RKI wird die Anzahl der Covid-19-Fälle genutzt, bei denen angegeben ist, dass sie sich in einer Klinik befinden. Entscheidend ist dabei das Meldedatum, nicht das Datum der Einweisung. Im Unterschied zur Zählweise in Bremen spielt es aber keine Rolle, ob eine Covid-19-Erkrankung auch Ursache des Krankenhausaufenthalts ist. Theoretisch würde ein symptomfreier coronapositiver Patient mit einem Beinbruch in der Hospitalisierungsinzidenz des RKI mitgezählt.

**Comment by ghost** [comment]
> Wo bist du denn? Kannst du einen Screenshot posten und eine Referenz, wie du auf die Abweichung kommst (Quelle)

Hier der Link zu den aktuellen Zahlen im Landkreis. 
https://www.schaumburg.de/Kurzmenü/Startseite/Corona-Fälle-Stand-25-11-2021.php?object=tx,3020.5&ModID=7&FID=3020.25202.1

<img width="1045" alt="Bildschirmfoto 2021-11-26 um 09 14 27" src="https://user-images.githubusercontent.com/83650650/143548616-a43db09b-15ca-48e7-96b8-8bbeaa6e894e.png">

Und der Screenshot von heute. 
![IMG_1854](https://user-images.githubusercontent.com/83650650/143548408-bb0c59f3-1b50-4837-8685-7a73450cf8fe.jpeg)

**Comment by ghost** [comment]
> > Das mit der Hospitalisierungsrate scheint aber noch Buggy zu sein. Bei mir wird 2.86 angezeigt obwohl wir bei über 6 sind.
> > Jemand ne idee?
> 
> Vermutlich vergleichst du die Hospitalisierungsinzidenz vom [RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) mit der vom [IVENA eHealth System](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html).
> 
> [Weser Kurier](https://www.weser-kurier.de/deutschland-welt/hospitalisierungsindex-so-unterschiedlich-sind-die-zaehlweisen-doc7ijeoq17mfp1mfb4ii1b):
> 
> > Anders als das RKI und einige andere Bundesländer bemisst Niedersachsen die Krankenhausinzidenz aufgrund der täglichen Meldungen über das Ivena-System nach der Zahl aller Neuaufnahmen von Covid-Patienten binnen der letzten sieben Tage. „Dabei spielt es keine Rolle, wann sich diese Patienten mit dem Virus infiziert haben“, erklärt eine Sprecherin von Gesundheitsministerin Daniela Behrens (SPD). Folge: Die RKI-Quoten für Niedersachsen sind durchweg niedriger als die Werte des Landes selbst.
> 
> In Niedersachsen wird auch nicht berücksichtigt wo die Patienten herkommen. Also wenn Niedersachsen 50 Leute aufnimmt aus anderen Bundesländern, dann steigt der Wert vom [IVENA eHealth System](https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html). Das lokale schwere Infektionsgeschehen wird damit dann allerdings nicht korrekt abgebildet.
> 
> Die Zählweise vom RKI ist auch nicht aussagekräftig, weil dort zählt jedes Intensivbett das positiv getestet ist, auch wenn die Person sich ein Bein gebrochen hat.
> 
> [Weser Kurier](https://www.weser-kurier.de/deutschland-welt/hospitalisierungsindex-so-unterschiedlich-sind-die-zaehlweisen-doc7ijeoq17mfp1mfb4ii1b):
> 
> > Für die Berechnung des RKI wird die Anzahl der Covid-19-Fälle genutzt, bei denen angegeben ist, dass sie sich in einer Klinik befinden. Entscheidend ist dabei das Meldedatum, nicht das Datum der Einweisung. Im Unterschied zur Zählweise in Bremen spielt es aber keine Rolle, ob eine Covid-19-Erkrankung auch Ursache des Krankenhausaufenthalts ist. Theoretisch würde ein symptomfreier coronapositiver Patient mit einem Beinbruch in der Hospitalisierungsinzidenz des RKI mitgezählt.

Das war mir bis jetzt gar nicht bekannt, danke.

**Comment by marcusraitner** [comment]
Dieses Datenchaos macht mich fertig hier in Deutschland 😩 leider kann ich da im Moment nichts machen.
