### ISSUE TITLE
Balken Impfung rechts: nur ein Wert und kein Symbol 

### ISSUE THREAD

**Issue by ParoTheParrot** [marcusraitner/COVID-19-Dashboard#84]
![2F427CAD-ED2E-4F39-987B-B8BDBB4D6977](https://user-images.githubusercontent.com/5046600/133122646-5378f358-5908-4660-9c74-e7a82be136b0.jpeg)

**Comment by marcusraitner** [comment]
Danke für den Hinweis. Ist ein bekanntes Problem der API (bzw. des RKI, das (a) diese Daten nur als Excel rausgibt und (b) dann ständig dran rumschraubt, aber lassen wir das). Ist schon fast behoben: https://github.com/marlon360/rki-covid-api/issues/280

**Comment by marcusraitner** [comment]
Die API funktioniert wieder.
