### ISSUE TITLE
Neue Farben: Pink ab 500 und Lila ab 1.000

### ISSUE THREAD

**Issue by ragalthar** [marcusraitner/COVID-19-Dashboard#89]
Hallo, das RKI hat zwei neue Farben: Pink ab einer 500er Inzidenz und ab einer 1.000er Inzidenz wird's Lola (siehe Screenshot)

![image](https://user-images.githubusercontent.com/82751561/142040022-55f55f91-6632-4e2c-a18e-6f3bfe1cd950.png)

Kannst du das in das Widget einbauen?

**Comment by marcusraitner** [comment]
Pink ab 500 gibt es schon im `theme=rki`

![image](https://user-images.githubusercontent.com/65543240/142042286-51e48d8b-e7ae-4be2-8c94-4f420997c902.jpeg)

Die 1000er Farbe baue ich nachher ein. Ist alles mittlerweile vorbereitet …

**Comment by 1rNidiD** [comment]
```
,
    {
      lower: 1000,
      color: new Color('#d80183', 1),
      highlight: new Color("#FFFFFF", .7)
    },
    {
      lower: 10000,
      color: new Color('#780175', 1),
      highlight: new Color("#FFFFFF", .7)
    }
```

Das ab Zeile 137 reinkopieren..

**Comment by marcusraitner** [comment]
Perfekt. Passiert nachher. Die 10.000er Grenze werden wir hoffentlich auf Landkreisebene nicht brauchen … da ist die Bandbreite der Faxinfrastruktur vermutlich der limitierende Faktor 😉

**Comment by 1rNidiD** [comment]
Wobei der Colorpicker nicht die richtigen Farben genommen hat.. die muss man ggf. noch anpassen und beim Original kann man ja auch andere Farben wählen.

**Comment by 1rNidiD** [comment]
![image](https://user-images.githubusercontent.com/47744797/142046666-f901a5ae-82c0-446d-a8a0-1760a99d00a8.jpeg)

So kommt's bei mir raus mit den Farben von oben...noch das passende Lila finden dann wärs okay denke ich.

**Comment by marcusraitner** [comment]
Sieht gut aus. Auch dass es langsam wieder nach unten geht bei euch und es noch freie Betten gibt 👍

**Comment by marcusraitner** [comment]
Schaut mal, ob das so passt.

**Comment by 1rNidiD** [comment]
Schaut perfekt aus! Danke!
Ja zum Glückwunsch gehts bissl runter bei uns...und die Impfquote steigt 💪🏻😊
