### ISSUE TITLE
Widget nur mit Hospitalisierungsinzidenz und Belegte Betten

### ISSUE THREAD

**Issue by compoundbow83** [marcusraitner/COVID-19-Dashboard#91]
Hallo, 
wäre es vielleicht möglich ein Widget zu erstellen, wo nur die Hospitalisierungssinzidenz und die belegten Betten angezeigt werden.

Also bitte nich falsch verstehen ich finde dieses Widget echt klasse. 

Aber ich würde gerne die oben erwähnten Daten in einem viereckigen Widget anzeigen und mit allen Daten ist das dann einfach viel zu klein.

Oder kennt jemand vieleicht schon so ein Widget?

Vielen Dank im Voraus.

**Comment by marcusraitner** [comment]
Du möchtest also ein Widget in der "kleinen" Größe (quadratisch) in dem nur die Hospitalisierungsinzidenz des Bundeslandes und die belegten Betten des Landkreises angezeigt werden? Grundsätzlich hatte ich mir schon vorgenommen auch die kleine Größe mal zu unterstützen, aber im Moment fehlt mir die Zeit … vielleicht ist das was für Weihnachten …

**Comment by compoundbow83** [comment]
Ja genau ein Widget in der "k.einen" Größe (quadratisch) 
Also ich hatte mir das ungefähr so vorgestellt.
- Hostpitalisierungsiszidenz des Bundeslandes
- Belegte Betten (durch Corona) des Bundeslandes
- die Impfquote des Bundeslandes
- muss nicht unbedingt sein, der "normale" Inzidenzwert des Bundeslandes

Also im Grunde gibt es ja alle Daten die ich meine in deinem Aktuellen Widget. 

Nur das in deinem Widget halt noch viel mehr Daten enthalten sind.

Das mit der Zeit kann ich natürlich gut verstehe 😉 Wenn du das aber wirklich mal umsetzen könntest, wäre das echt super.
