### ISSUE TITLE
Error on line 662:63: TypeError: undefined is not an object (evaluating 'hospitalizationData.dat [bundesLand]') 

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#92]
Bekomme seit heute die o.g. Fehlermeldung. Eine Idee was zu tun ist?
Danke im Voraus!

**Comment by tomads** [comment]
dito

**Comment by blade1986ak** [comment]
Ja ich auch

**Comment by icsAT** [comment]
Es gab heute Morgen Probleme beim RKI mit der API. Diese sind zwischenzeitlich behoben. Da hier nicht direkt auf das RKI zugegriffen wird, ist zu vermuten, dass es an der verwendeten API liegt, die noch mit den RKI Problemen kämpft ;-) Ich wurde sagen abwarten und nen guten Tee oder so trinken. Spätestens morgen ist bestimmt wieder alles gut.

**Comment by marcusraitner** [comment]
Ja, ich habe dasselbe Problem. Habe bei der API einen Issue aufgemacht: https://github.com/marlon360/rki-covid-api/issues/345

**Comment by marcusraitner** [comment]
Bei mir geht es wieder

**Comment by lululasse** [comment]
Yep! Alles gut! 
Danke für dieses tolle Widget!

**Comment by marcusraitner** [comment]
Gerne! Jetzt brauchen wir beim RKI bloß noch tolle Schnittstellen 😂
