### ISSUE TITLE
Inzidenz bei 1000+ ohne Kommastellen möglich?

### ISSUE THREAD

**Issue by youmakemyday** [marcusraitner/COVID-19-Dashboard#94]
Servus Marcus,

Ist es möglich bei vierstelligen Inzidenzen die Nachkommastellen wegzulassen? Aktuell überlagert sich das auf einem iPhone SE/2020 weil der Platz zu knapp ist ;)

Grüße ymmD

**Comment by marcusraitner** [comment]
Sehr gute Idee. Schaue ich mir an. Ich frage mich, ob es nicht schon bei dreistelligen Zahlen Sinn macht.

**Comment by youmakemyday** [comment]
Find ich auch, alles ab 100+ ohne Kommastellen klingt gut. Meinst du findest irgendwo noch ein kleines Plätzchen für die Hospitalisierungsinzidenz des Bundeslandes? Daten wären jedenfalls auch über RKI verfügbar.

**Comment by marcusraitner** [comment]
Aber die Hospitalisierungsinzidenz zeige ich doch schon rechts unten an. Hast du das gesehen?

**Comment by youmakemyday** [comment]
ah stimmt, ich Blindfisch 😂

**Comment by marcusraitner** [comment]
Ist jetzt behoben. Bitte prüfen.

**Comment by youmakemyday** [comment]
klappt, ganz dickes DANKESCHÖN nach EBE

**Comment by marcusraitner** [comment]
Grüße zurück!
