### ISSUE TITLE
Android-Version

### ISSUE THREAD

**Issue by shivan** [marcusraitner/COVID-19-Dashboard#95]
Hi,

cooles Teil. Kann ich das auch irgendwie auf Android zum Laufen bringen?

**Comment by marcusraitner** [comment]
> cooles Teil. Kann ich das auch irgendwie auf Android zum Laufen bringen?

Danke! 

Wenn es ein Äquivalent für Scriptable gäbe, dann vielleicht. Sieht aber nicht so aus im Moment https://www.reddit.com/r/Scriptable/comments/npxm42/android/?utm_source=share&utm_medium=mweb3x

**Comment by shivan** [comment]
Hi,

ich hab Simon B. Støvring angeschrieben...

> Thanks. There is no Android version of Scriptable and I have no plans to make one as it rely heavily on frameworks provided by Apple on iOS.

Sieht also bisher nicht so aus... aber wer weiß, vielleicht findet sich irgendwann jemand, der Scriptable auf Android nachbaut... Weil prinzipiell ist es ja nur HTML + JS + CSS... ;-)

**Comment by marcusraitner** [comment]
Es ist bestimmt möglich, aber solange es nicht etwas Ähnliches wie Scriptable gibt ist es mühsam. Ich schließe den Issue damit erst mal.
