### ISSUE TITLE
Neuinfekttionen für aktuellen Tag

### ISSUE THREAD

**Issue by mappledp** [marcusraitner/COVID-19-Dashboard#96]
Hallo,
vorab super Widget. Großes Lob und vielen Dank.
Ist es möglich die Zahl der gemeldeten Neuinfektionen auch für den aktuellen Tag anzeigen zu lassen?
Danke und VG

**Comment by marcusraitner** [comment]
Vielen Dank! Die Neuinfektionen für den aktuellen Tag stehen aber doch erst am Ende des Tages fest, oder? Oder ist gemeint quasi in Echtzeit die aktuellen Infektionen des Tages anzuzeigen? Ich wüsste allerdings nicht aus welcher Quelle in diesem Land wo wir nach 20 Monaten diese Zahlen via Excel verteilt bekommen.

**Comment by mappledp** [comment]
So gesehen ist das richtig. Andere Widgets zeigen dann für den aktuellen Tag die Daten vom Vortag an. Das hab ich falsch interpretiert. 
Daher sehe ich auch keinen Handlungsbedarf.

**Comment by marcusraitner** [comment]
Danke, dann schließe ich das jetzt.
