### ISSUE TITLE
Fehler bei Frozen=Y

### ISSUE THREAD

**Issue by Lutti45** [marcusraitner/COVID-19-Dashboard#97]
Hallo Marcus,

erstmal Danke für das Super-Widget. Ich habe ein Problem mit dem Parameter „Frozen=y“. Es fehlen da einige Tage.

![IMG_1168](https://user-images.githubusercontent.com/78354875/144383489-3e212d77-5a2e-4980-9d57-35884cfd2c27.jpeg)

Weiter habe ich eine Frage, ist es möglich auch die Booster-Impfung anzuzeigen?

LG Lutti45

**Comment by toddy1986** [comment]
Da kann ich helfen, da ich auch drüber gestolpert bin. Das RKI aktualisiert das Excel seid ca einer Woche nur noch wöchentlich an einem Donnerstag. Es ist echt unbegreiflich im Moment.

Siehe https://github.com/marlon360/rki-covid-api/issues/351

**Comment by marcusraitner** [comment]
Danke für die Hilfe @toddy1986 

Es ist tatsächlich unbegreiflich. Wer braucht im Moment schon verlässliche und aktuelle Daten … Es scheint leider immer weniger um Daten und Fakten zu gehen als vielmehr um Meinungen und Positionen.

**Comment by marcusraitner** [comment]
Vielleicht noch eine Erklärung, warum der aktuelle Tag trotzdem angezeigt wird: Der stammt aus anderer Quelle und ich habe den eingebaut, damit es mit der Darstellung `frozen=n` konsistent ist.

**Comment by Lutti45** [comment]
Danke für die Aufklärung. Ich gebe euch Recht, wer braucht schon aktuelle Daten. 🤢

**Comment by ghostmju** [comment]
Danke für die Erläuterungen, frozen=y war für mich am interessantesten, weil das ja die Massnahmen steuerte…
An sich kann man die Funktion jetzt rausnehmen… - oder alle nicht gelieferten Tage mit einem „?“ statt Balken darstellen (vielleicht wird die Exceltabelle irgendwann wieder öfter gepflegt)…

**Comment by Rubber1Duck** [comment]
Es hat ewig lange gedauert (5 Monate) und eigentlich ist der frozen incidence Wert auch garnicht mehr so wichtig, aber ich habe endlich eine Lösung für die rki-covid-api gefunden!
Sofern Marlon dem PR zustimmt werden die Werte jeweils seit letztem Montag wieder verfügbar sein!

**Comment by marcusraitner** [comment]
Cool! Danke dir.

**Comment by Rubber1Duck** [comment]
Von der api Seite aus ist das gefixed!

**Comment by marcusraitner** [comment]
Stimmt. Funktioniert auch schon länger wieder. Hatte ich vergessen zu schließen
