### ISSUE TITLE
Booster Quote

### ISSUE THREAD

**Issue by lululasse** [marcusraitner/COVID-19-Dashboard#98]
Hi Marcus, kannst Du die Booster Quote noch irgendwie integrieren?
Danke im Voraus!

**Comment by marcusraitner** [comment]
Ja, das könnte ich eigentlich machen; die Daten hätte ich in der API mittlerweile. Aber wohin soll ich dann bloß die Hospitalisierungsanzeige machen … oder es wird ein entweder-oder …

**Comment by jseegger** [comment]
Hallo Marcus,

mach doch den Balken der Intensivbetten etwas schmäler (z. B. auf die Breite der LK Inzidenzbalken). 
In den freien Platz dann die Hospitalisierungsrate (evtl. auch die vom Bundesland und Deutschland unterhalb der entsprechenden Inzidenzbalken)
Dann wäre rechts im Impfstatus Platz für die Boosterinformation und alles wäre thematisch geordneter 😉

Gruß 
Jürgen

**Comment by marcusraitner** [comment]
> mach doch den Balken der Intensivbetten etwas schmäler (z. B. auf die Breite der LK Inzidenzbalken). In den freien Platz dann die Hospitalisierungsrate (evtl. auch die vom Bundesland und Deutschland unterhalb der entsprechenden Inzidenzbalken) Dann wäre rechts im Impfstatus Platz für die Boosterinformation und alles wäre thematisch geordneter 😉

Danke für die Idee, Jürgen. Einerseits würde es thematisch dann besser passen, andererseits würde dann Information zu Bayern bei den Betten für den Landkreis stehen (ok, das ist bei Inzidenz für Bayern drüber auch so); müsste ich evtl. kenntlich machen.

**Comment by lululasse** [comment]
Marcus,

nochmals schönen Dank für dieses tolle und informative Widget.
Ich wollte nochmals höflich nachfragen, ob Du noch an der Integration der Booster Impfquote arbeitest?

Beste Grüße
Klaus

**Comment by marcusraitner** [comment]
> Marcus,
> 
> nochmals schönen Dank für dieses tolle und informative Widget. Ich wollte nochmals höflich nachfragen, ob Du noch an der Integration der Booster Impfquote arbeitest?
> 
> Beste Grüße Klaus

Hallo Klaus, danke für die Erinnerung. Arbeiten ist zu viel gesagt, es steht auf meiner To-Do-Liste ;-)

**Comment by marcusraitner** [comment]
Wäre das eine Lösung? Ein bisschen hübscher mache ich es noch …

![image](https://user-images.githubusercontent.com/65543240/146828743-5fc9bfb2-d4c2-4bf0-a9c2-9d07e79313a9.jpeg)

**Comment by lululasse** [comment]
Sehr cool! 👍

**Comment by ghost** [comment]
> Wäre das eine Lösung? Ein bisschen hübscher mache ich es noch …
> 
> ![image](https://user-images.githubusercontent.com/65543240/146828743-5fc9bfb2-d4c2-4bf0-a9c2-9d07e79313a9.jpeg)

Das ist Stark 👍🏼

**Comment by marcusraitner** [comment]
Ist jetzt eingecheckt. Probiert es doch mal aus.

**Comment by lululasse** [comment]
Perfekt, Marcus! 
Danke und schöne geruhsame Festtage!
